AWSTemplateFormatVersion: '2010-09-09'
Description: EVO Platform - Nested Stack

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  RestApiId:
    Type: String
  FunctionsResourceId:
    Type: String
  AuthorizerId:
    Type: String
  LambdaCodeBucket:
    Type: String
  LambdaExecutionRoleArn:
    Type: String
  LambdaSecurityGroupIds:
    Type: CommaDelimitedList
  PrivateSubnetIds:
    Type: CommaDelimitedList
  LambdaLayerArn:
    Type: String
  DatabaseUrl:
    Type: String
    NoEcho: true
  CognitoUserPoolId:
    Type: String

Resources:
  CheckMigrationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-check-migrations'
      Runtime: nodejs18.x
      Handler: check-migrations.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/check-migrations.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 30
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  DbInitFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-db-init'
      Runtime: nodejs18.x
      Handler: db-init.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/db-init.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 300
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  ListTablesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-list-tables'
      Runtime: nodejs18.x
      Handler: list-tables.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/list-tables.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 30
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  RunMigrationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-run-migrations'
      Runtime: nodejs18.x
      Handler: run-migrations.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/run-migrations.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 300
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  RunSqlMigrationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-run-sql-migration'
      Runtime: nodejs18.x
      Handler: run-sql-migration.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/run-sql-migration.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 300
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  DbInitResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref FunctionsResourceId
      PathPart: db-init

  DbInitOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DbInitResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Requested-With,X-API-Key,X-Request-ID,X-CSRF-Token,X-Correlation-ID,X-Amz-Date,X-Amz-Security-Token,X-Impersonate-Organization'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  DbInitPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DbInitResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DbInitFunction.Arn}/invocations'

  DbInitPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DbInitFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/api/functions/db-init'

Outputs:
  CheckMigrationsFunctionArn:
    Value: !GetAtt CheckMigrationsFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-check-migrations-arn'
  DbInitFunctionArn:
    Value: !GetAtt DbInitFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-db-init-arn'
  ListTablesFunctionArn:
    Value: !GetAtt ListTablesFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-list-tables-arn'
  RunMigrationsFunctionArn:
    Value: !GetAtt RunMigrationsFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-run-migrations-arn'
  RunSqlMigrationFunctionArn:
    Value: !GetAtt RunSqlMigrationFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-run-sql-migration-arn'