AWSTemplateFormatVersion: '2010-09-09'
Description: EVO Platform - Nested Stack

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  RestApiId:
    Type: String
  FunctionsResourceId:
    Type: String
  AuthorizerId:
    Type: String
  LambdaCodeBucket:
    Type: String
  LambdaExecutionRoleArn:
    Type: String
  LambdaSecurityGroupIds:
    Type: CommaDelimitedList
  PrivateSubnetIds:
    Type: CommaDelimitedList
  LambdaLayerArn:
    Type: String
  DatabaseUrl:
    Type: String
    NoEcho: true
  CognitoUserPoolId:
    Type: String

Resources:
  AiPrioritizationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-ai-prioritization'
      Runtime: nodejs18.x
      Handler: ai-prioritization.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/ai-prioritization.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 120
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  DetectAnomaliesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-detect-anomalies'
      Runtime: nodejs18.x
      Handler: detect-anomalies.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/detect-anomalies.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 120
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  GenerateAiInsightsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-generate-ai-insights'
      Runtime: nodejs18.x
      Handler: generate-ai-insights.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/generate-ai-insights.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 120
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  IntelligentAlertsAnalyzerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-intelligent-alerts-analyzer'
      Runtime: nodejs18.x
      Handler: intelligent-alerts-analyzer.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/intelligent-alerts-analyzer.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 120
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  PredictIncidentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-predict-incidents'
      Runtime: nodejs18.x
      Handler: predict-incidents.handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub 'lambdas/predict-incidents.zip'
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 120
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds: !Ref LambdaSecurityGroupIds
        SubnetIds: !Ref PrivateSubnetIds
      Layers:
        - !Ref LambdaLayerArn
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_PATH: /opt/nodejs/node_modules
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
  DetectAnomaliesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref FunctionsResourceId
      PathPart: detect-anomalies

  DetectAnomaliesOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DetectAnomaliesResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Requested-With,X-API-Key,X-Request-ID,X-CSRF-Token,X-Correlation-ID,X-Amz-Date,X-Amz-Security-Token,X-Impersonate-Organization'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  DetectAnomaliesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref DetectAnomaliesResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DetectAnomaliesFunction.Arn}/invocations'

  DetectAnomaliesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DetectAnomaliesFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/api/functions/detect-anomalies'
  IntelligentAlertsAnalyzerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref FunctionsResourceId
      PathPart: intelligent-alerts-analyzer

  IntelligentAlertsAnalyzerOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref IntelligentAlertsAnalyzerResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Requested-With,X-API-Key,X-Request-ID,X-CSRF-Token,X-Correlation-ID,X-Amz-Date,X-Amz-Security-Token,X-Impersonate-Organization'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  IntelligentAlertsAnalyzerPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref IntelligentAlertsAnalyzerResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IntelligentAlertsAnalyzerFunction.Arn}/invocations'

  IntelligentAlertsAnalyzerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IntelligentAlertsAnalyzerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/api/functions/intelligent-alerts-analyzer'
  PredictIncidentsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref FunctionsResourceId
      PathPart: predict-incidents

  PredictIncidentsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref PredictIncidentsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Requested-With,X-API-Key,X-Request-ID,X-CSRF-Token,X-Correlation-ID,X-Amz-Date,X-Amz-Security-Token,X-Impersonate-Organization'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  PredictIncidentsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref PredictIncidentsResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PredictIncidentsFunction.Arn}/invocations'

  PredictIncidentsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PredictIncidentsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/api/functions/predict-incidents'

Outputs:
  AiPrioritizationFunctionArn:
    Value: !GetAtt AiPrioritizationFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ai-prioritization-arn'
  DetectAnomaliesFunctionArn:
    Value: !GetAtt DetectAnomaliesFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-detect-anomalies-arn'
  GenerateAiInsightsFunctionArn:
    Value: !GetAtt GenerateAiInsightsFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-generate-ai-insights-arn'
  IntelligentAlertsAnalyzerFunctionArn:
    Value: !GetAtt IntelligentAlertsAnalyzerFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-intelligent-alerts-analyzer-arn'
  PredictIncidentsFunctionArn:
    Value: !GetAtt PredictIncidentsFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-predict-incidents-arn'