AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless Web Application with Lambda, API Gateway, Route53 and SSL'

Parameters:
  AppName:
    Type: String
    Default: demo-app
    Description: Name of the application
  
  SubDomain:
    Type: String
    Default: demo
    Description: Subdomain for the application (will be subdomain.ai.udstec.io)
  
  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:383234048592:certificate/4243e02e-ee0c-4b7a-b5b4-bca7adf31a70
    Description: ACM Certificate ARN for SSL
  
  HostedZoneId:
    Type: String
    Default: Z025830736D37OCK2Z2QR
    Description: Route53 Hosted Zone ID
  
  DomainName:
    Type: String
    Default: ai.udstec.io
    Description: Base domain name

Resources:
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-lambda-role'

  # Lambda Function
  AppLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AppName}-function'
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          
          def handler(event, context):
              # Get request details
              http_method = event.get('httpMethod', 'GET')
              path = event.get('path', '/')
              query_params = event.get('queryStringParameters') or {}
              
              # HTML response
              html_content = '''
              <!DOCTYPE html>
              <html lang="pt-BR">
              <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>Demo App - Serverless</title>
                  <style>
                      * { margin: 0; padding: 0; box-sizing: border-box; }
                      body {
                          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                          min-height: 100vh;
                          display: flex;
                          align-items: center;
                          justify-content: center;
                      }
                      .container {
                          background: white;
                          padding: 3rem;
                          border-radius: 20px;
                          box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
                          text-align: center;
                          max-width: 500px;
                      }
                      h1 {
                          color: #1a202c;
                          margin-bottom: 1rem;
                          font-size: 2.5rem;
                      }
                      .status {
                          background: #48bb78;
                          color: white;
                          padding: 0.5rem 1.5rem;
                          border-radius: 50px;
                          display: inline-block;
                          margin: 1rem 0;
                          font-weight: 600;
                      }
                      .info {
                          color: #718096;
                          margin-top: 1.5rem;
                          line-height: 1.8;
                      }
                      .tech {
                          display: flex;
                          justify-content: center;
                          gap: 1rem;
                          margin-top: 2rem;
                          flex-wrap: wrap;
                      }
                      .tech span {
                          background: #edf2f7;
                          padding: 0.5rem 1rem;
                          border-radius: 8px;
                          font-size: 0.875rem;
                          color: #4a5568;
                      }
                  </style>
              </head>
              <body>
                  <div class="container">
                      <h1>🚀 Demo App</h1>
                      <div class="status">✓ Online</div>
                      <p class="info">
                          Aplicação serverless implantada com sucesso!<br>
                          Rodando 100% em AWS Lambda.
                      </p>
                      <div class="tech">
                          <span>AWS Lambda</span>
                          <span>API Gateway</span>
                          <span>Route53</span>
                          <span>SSL/TLS</span>
                      </div>
                  </div>
              </body>
              </html>
              '''
              
              # API endpoint
              if path.startswith('/api'):
                  return {
                      'statusCode': 200,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*'
                      },
                      'body': json.dumps({
                          'status': 'success',
                          'message': 'API funcionando!',
                          'method': http_method,
                          'path': path,
                          'query': query_params
                      })
                  }
              
              # HTML response for root
              return {
                  'statusCode': 200,
                  'headers': {
                      'Content-Type': 'text/html; charset=utf-8'
                  },
                  'body': html_content
              }
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-function'

  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${AppName}-api'
      Description: API Gateway for serverless application
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-api'

  # API Gateway Resource (proxy)
  ApiGatewayProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method for Root
  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AppLambdaFunction.Arn}/invocations'

  # API Gateway Method for Proxy
  ApiGatewayProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AppLambdaFunction.Arn}/invocations'

  # Lambda Permission for API Gateway
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayRootMethod
      - ApiGatewayProxyMethod
    Properties:
      RestApiId: !Ref ApiGateway

  # API Gateway Stage
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiGatewayDeployment
      StageName: prod
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-stage'

  # Custom Domain Name
  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      RegionalCertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2
      Tags:
        - Key: Name
          Value: !Sub '${SubDomain}.${DomainName}'

  # Base Path Mapping
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ApiGatewayStage
    Properties:
      DomainName: !Ref ApiCustomDomain
      RestApiId: !Ref ApiGateway
      Stage: prod

  # Route53 Record
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '${SubDomain}.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId

Outputs:
  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
  
  CustomDomainUrl:
    Description: Custom Domain URL
    Value: !Sub 'https://${SubDomain}.${DomainName}'
  
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt AppLambdaFunction.Arn
  
  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref ApiGateway
