AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL Database for EVO UDS System'

Parameters:
  VpcId:
    Type: String
    Description: VPC ID for the database
  DatabaseSubnetGroupName:
    Type: String
    Description: Database subnet group name
  DatabaseSecurityGroupId:
    Type: String
    Description: Database security group ID

Resources:
  # Database Secret
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /evo-uds/database/credentials
      Description: Database credentials for EVO UDS
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # RDS Database
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: evo-uds-dev
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '15.4'
      AllocatedStorage: 20
      StorageType: gp2
      StorageEncrypted: true
      
      DBName: evouds
      MasterUsername: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}'
      
      VPCSecurityGroups:
        - !ImportValue EvoUds-DatabaseSecurityGroupId
      DBSubnetGroupName: !ImportValue EvoUds-DatabaseSubnetGroupName
      
      BackupRetentionPeriod: 7
      DeleteAutomatedBackups: true
      DeletionProtection: false
      
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      
      Tags:
        - Key: Name
          Value: EvoUds-Database
        - Key: Environment
          Value: development

  # Secret Attachment
  SecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DatabaseSecret
      TargetId: !Ref Database
      TargetType: AWS::RDS::DBInstance

Outputs:
  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: EvoUds-DatabaseEndpoint

  DatabasePort:
    Description: Database port
    Value: !GetAtt Database.Endpoint.Port
    Export:
      Name: EvoUds-DatabasePort

  DatabaseSecretArn:
    Description: Database secret ARN
    Value: !Ref DatabaseSecret
    Export:
      Name: EvoUds-DatabaseSecretArn

  DatabaseName:
    Description: Database name
    Value: evouds
    Export:
      Name: EvoUds-DatabaseName