/**
 * Security Engine V2 - AWS Client Factory
 * Lazy loading and connection pooling for AWS SDK clients
 */
import { EC2Client } from '@aws-sdk/client-ec2';
import { RDSClient } from '@aws-sdk/client-rds';
import { S3Client } from '@aws-sdk/client-s3';
import { IAMClient } from '@aws-sdk/client-iam';
import { LambdaClient } from '@aws-sdk/client-lambda';
import { EKSClient } from '@aws-sdk/client-eks';
import { ECSClient } from '@aws-sdk/client-ecs';
import { ECRClient } from '@aws-sdk/client-ecr';
import { SecretsManagerClient } from '@aws-sdk/client-secrets-manager';
import { KMSClient } from '@aws-sdk/client-kms';
import { CloudTrailClient } from '@aws-sdk/client-cloudtrail';
import { GuardDutyClient } from '@aws-sdk/client-guardduty';
import { SecurityHubClient } from '@aws-sdk/client-securityhub';
import { WAFV2Client } from '@aws-sdk/client-wafv2';
import { APIGatewayClient } from '@aws-sdk/client-api-gateway';
import { ApiGatewayV2Client } from '@aws-sdk/client-apigatewayv2';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { ElastiCacheClient } from '@aws-sdk/client-elasticache';
import { CloudFrontClient } from '@aws-sdk/client-cloudfront';
import { ElasticLoadBalancingV2Client } from '@aws-sdk/client-elastic-load-balancing-v2';
import { SNSClient } from '@aws-sdk/client-sns';
import { SQSClient } from '@aws-sdk/client-sqs';
import { ACMClient } from '@aws-sdk/client-acm';
import { CognitoIdentityProviderClient } from '@aws-sdk/client-cognito-identity-provider';
import { OpenSearchClient } from '@aws-sdk/client-opensearch';
import { CloudWatchLogsClient } from '@aws-sdk/client-cloudwatch-logs';
import { CloudWatchClient } from '@aws-sdk/client-cloudwatch';
import { ConfigServiceClient } from '@aws-sdk/client-config-service';
import { BackupClient } from '@aws-sdk/client-backup';
import { RedshiftClient } from '@aws-sdk/client-redshift';
import { Route53Client } from '@aws-sdk/client-route-53';
import { EFSClient } from '@aws-sdk/client-efs';
import { EventBridgeClient } from '@aws-sdk/client-eventbridge';
import { SFNClient } from '@aws-sdk/client-sfn';
import { SSMClient } from '@aws-sdk/client-ssm';
import { KinesisClient } from '@aws-sdk/client-kinesis';
import { FirehoseClient } from '@aws-sdk/client-firehose';
import { Inspector2Client } from '@aws-sdk/client-inspector2';
import { Macie2Client } from '@aws-sdk/client-macie2';
import { NetworkFirewallClient } from '@aws-sdk/client-network-firewall';
import { OrganizationsClient } from '@aws-sdk/client-organizations';
import { AccessAnalyzerClient } from '@aws-sdk/client-accessanalyzer';
import { GlueClient } from '@aws-sdk/client-glue';
import { STSClient } from '@aws-sdk/client-sts';
import type { AWSCredentials } from '../types.js';
export declare class AWSClientFactory {
    private clients;
    private credentials;
    private resolvedCredentials;
    constructor(credentials: AWSCredentials);
    private resolveCredentials;
    private getClientConfig;
    private getClientKey;
    getEC2Client(region: string): Promise<EC2Client>;
    getRDSClient(region: string): Promise<RDSClient>;
    getS3Client(region?: string): Promise<S3Client>;
    getIAMClient(): Promise<IAMClient>;
    getLambdaClient(region: string): Promise<LambdaClient>;
    getEKSClient(region: string): Promise<EKSClient>;
    getECSClient(region: string): Promise<ECSClient>;
    getECRClient(region: string): Promise<ECRClient>;
    getSecretsManagerClient(region: string): Promise<SecretsManagerClient>;
    getKMSClient(region: string): Promise<KMSClient>;
    getCloudTrailClient(region: string): Promise<CloudTrailClient>;
    getGuardDutyClient(region: string): Promise<GuardDutyClient>;
    getSecurityHubClient(region: string): Promise<SecurityHubClient>;
    getWAFV2Client(region: string): Promise<WAFV2Client>;
    getAPIGatewayClient(region: string): Promise<APIGatewayClient>;
    getApiGatewayV2Client(region: string): Promise<ApiGatewayV2Client>;
    getDynamoDBClient(region: string): Promise<DynamoDBClient>;
    getElastiCacheClient(region: string): Promise<ElastiCacheClient>;
    getCloudFrontClient(): Promise<CloudFrontClient>;
    getELBV2Client(region: string): Promise<ElasticLoadBalancingV2Client>;
    getSNSClient(region: string): Promise<SNSClient>;
    getSQSClient(region: string): Promise<SQSClient>;
    getACMClient(region: string): Promise<ACMClient>;
    getCognitoClient(region: string): Promise<CognitoIdentityProviderClient>;
    getOpenSearchClient(region: string): Promise<OpenSearchClient>;
    getCloudWatchLogsClient(region: string): Promise<CloudWatchLogsClient>;
    getConfigClient(region: string): Promise<ConfigServiceClient>;
    getCloudWatchClient(region: string): Promise<CloudWatchClient>;
    getBackupClient(region: string): Promise<BackupClient>;
    getRedshiftClient(region: string): Promise<RedshiftClient>;
    getRoute53Client(): Promise<Route53Client>;
    getEFSClient(region: string): Promise<EFSClient>;
    getEventBridgeClient(region: string): Promise<EventBridgeClient>;
    getStepFunctionsClient(region: string): Promise<SFNClient>;
    getSSMClient(region: string): Promise<SSMClient>;
    getKinesisClient(region: string): Promise<KinesisClient>;
    getFirehoseClient(region: string): Promise<FirehoseClient>;
    getInspectorClient(region: string): Promise<Inspector2Client>;
    getMacieClient(region: string): Promise<Macie2Client>;
    getNetworkFirewallClient(region: string): Promise<NetworkFirewallClient>;
    getOrganizationsClient(): Promise<OrganizationsClient>;
    getAccessAnalyzerClient(region: string): Promise<AccessAnalyzerClient>;
    getGlueClient(region: string): Promise<GlueClient>;
    getSTSClient(region?: string): Promise<STSClient>;
    getAccountId(): Promise<string>;
    clearClients(): void;
    getClientCount(): number;
}
//# sourceMappingURL=client-factory.d.ts.map