AWSTemplateFormatVersion: '2010-09-09'
Description: |
  EVO Platform - SSM Bastion for secure DB tunnel
  t4g.nano ARM (~$3/mês), sem SSH, sem portas abertas
  Usa SSM Session Manager para port forwarding seguro

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [sandbox, production]
  ProjectName:
    Type: String
    Default: evo-uds-v3
  VpcId:
    Type: String
    Description: VPC ID where RDS lives
  PublicSubnetId:
    Type: String
    Description: Public subnet for bastion (needs internet for SSM)
  DatabaseSecurityGroupId:
    Type: String
    Description: RDS security group ID (bastion will be allowed to connect)

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSM Bastion - no inbound ports needed
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound (SSM + RDS)
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-bastion-sg'

  # Allow bastion to reach RDS
  DatabaseIngressFromBastion:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DatabaseSecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref BastionSecurityGroup
      Description: Allow PostgreSQL from SSM Bastion

  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-bastion-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-bastion-role'

  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BastionRole

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.nano
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      IamInstanceProfile: !Ref BastionInstanceProfile
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-ssm-bastion'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: DB-Tunnel

Outputs:
  BastionInstanceId:
    Description: Instance ID for SSM port forwarding
    Value: !Ref BastionInstance
    Export:
      Name: !Sub '${ProjectName}-${Environment}-bastion-id'
  
  TunnelCommand:
    Description: Command to start DB tunnel
    Value: !Sub |
      aws ssm start-session --target ${BastionInstance} --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters '{"host":["<RDS_ENDPOINT>"],"portNumber":["5432"],"localPortNumber":["5432"]}'
