AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for Security Engine cache persistence across Lambda cold starts'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name

  TableName:
    Type: String
    Default: evo-security-scan-cache
    Description: Name of the DynamoDB table

  TTLDays:
    Type: Number
    Default: 1
    Description: Number of days to keep cache entries (TTL)

Resources:
  SecurityCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: security-engine
        - Key: Purpose
          Value: cache-persistence

Outputs:
  TableName:
    Description: Name of the DynamoDB cache table
    Value: !Ref SecurityCacheTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the DynamoDB cache table
    Value: !GetAtt SecurityCacheTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
