AWSTemplateFormatVersion: '2010-09-09'
Description: |
  EVO Platform - CloudWatch Logs Destination for Cross-Account WAF Log Streaming.
  Deploy this stack in EACH region where customers have WAF resources.
  Regional destinations forward logs to the central waf-log-processor in us-east-1.

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - sandbox

  ProjectName:
    Type: String
    Default: evo-uds-v3

  WafLogProcessorArn:
    Type: String
    Default: arn:aws:lambda:us-east-1:523115032346:function:evo-uds-v3-production-waf-log-processor
    Description: ARN of the central WAF Log Processor Lambda in us-east-1

Resources:
  # Forwarder Lambda — receives logs from destination, forwards to central processor
  WafLogForwarderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-waf-fwd-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: InvokeCentralProcessor
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !Ref WafLogProcessorArn

  WafLogForwarderFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-waf-fwd-${AWS::Region}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt WafLogForwarderRole.Arn
      Timeout: 60
      MemorySize: 128
      Architectures: [arm64]
      Environment:
        Variables:
          CENTRAL_PROCESSOR_ARN: !Ref WafLogProcessorArn
      Code:
        ZipFile: |
          const { LambdaClient, InvokeCommand } = require('@aws-sdk/client-lambda');
          const client = new LambdaClient({ region: 'us-east-1' });
          exports.handler = async (event) => {
            await client.send(new InvokeCommand({
              FunctionName: process.env.CENTRAL_PROCESSOR_ARN,
              InvocationType: 'Event',
              Payload: JSON.stringify(event),
            }));
          };

  WafLogForwarderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt WafLogForwarderFunction.Arn
      Action: lambda:InvokeFunction
      Principal: !Sub 'logs.${AWS::Region}.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'

  # IAM Role for Destination to invoke the forwarder Lambda
  WafLogsDestinationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-waf-dest-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt WafLogForwarderFunction.Arn

  # CloudWatch Logs Destination — customers' subscription filters point here
  WafLogsDestination:
    Type: AWS::Logs::Destination
    DependsOn: [WafLogsDestinationRole, WafLogForwarderPermission]
    Properties:
      DestinationName: !Sub '${ProjectName}-${Environment}-waf-logs-destination'
      RoleArn: !GetAtt WafLogsDestinationRole.Arn
      TargetArn: !GetAtt WafLogForwarderFunction.Arn
      DestinationPolicy: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowCrossAccountSubscription",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "logs:PutSubscriptionFilter",
              "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:destination:${ProjectName}-${Environment}-waf-logs-destination"
            }
          ]
        }

Outputs:
  WafLogsDestinationArn:
    Value: !GetAtt WafLogsDestination.Arn
  WafLogsDestinationName:
    Value: !Sub '${ProjectName}-${Environment}-waf-logs-destination'
  Region:
    Value: !Ref 'AWS::Region'
