AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  EVO Platform - Test Single Lambda with esbuild
  Testing esbuild build before full deployment

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [sandbox, production]
  
  ProjectName:
    Type: String
    Default: evo-uds-v3

  DatabasePassword:
    Type: String
    NoEcho: true
    Default: "placeholder"
    Description: Database password (not used in this test)

Resources:
  # Single Lambda for testing esbuild
  ValidateLicenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-prod-validate-license-test'
      CodeUri: backend/src/handlers/license/
      Handler: validate-license.handler
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          NODE_ENV: production
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - validate-license.ts
        External:
          - '@prisma/client'
          - '.prisma/client'
          - '@aws-sdk/*'

Outputs:
  ValidateLicenseFunctionArn:
    Description: ARN of the ValidateLicense function
    Value: !GetAtt ValidateLicenseFunction.Arn
