version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing esbuild globally..."
      - npm install -g esbuild
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - npm run prisma:generate --prefix backend

  pre_build:
    commands:
      - echo "=== Validating Lambda imports ==="
      - npx --prefix backend tsx scripts/validate-lambda-imports.ts
      - echo "=== Fetching git history for change detection ==="
      - |
        # Determine the branch we're on
        CURRENT_BRANCH="${CODEBUILD_WEBHOOK_HEAD_REF:-}"
        if [ -z "$CURRENT_BRANCH" ]; then
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")
        fi
        # Strip refs/heads/ prefix if present
        CURRENT_BRANCH="${CURRENT_BRANCH#refs/heads/}"
        echo "Current branch: $CURRENT_BRANCH"

        GIT_DIFF_OK="false"
        if [ -d ".git" ]; then
          echo "Git repo detected (CODEBUILD_CLONE_REF mode)"
          git fetch --deepen=2 2>/dev/null || \
            git fetch --unshallow 2>/dev/null || \
            git fetch --depth=5 origin "$CURRENT_BRANCH" 2>/dev/null || \
            git fetch --depth=5 2>/dev/null || \
            echo "WARNING: All git fetch attempts failed"

          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            GIT_DIFF_OK="true"
            echo "Git history OK - can diff HEAD~1..HEAD"
          else
            echo "WARNING: Cannot resolve HEAD~1 - shallow clone too shallow"
          fi
        else
          echo "No .git directory - will do full deploy"
        fi

        if [ "$GIT_DIFF_OK" = "true" ]; then
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "FULL_DEPLOY")
        else
          CHANGED_FILES="FULL_DEPLOY"
        fi

        echo "$CHANGED_FILES" > /tmp/changed_files.txt
        echo "Changed files:"
        cat /tmp/changed_files.txt

      - echo "=== Determining environment ==="
      - export ENV="${ENVIRONMENT:-sandbox}"
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          export STACK_NAME="evo-uds-v3-prod-lambdas"
          export COGNITO_USER_POOL_ID="us-east-1_BUJecylbm"
          export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:523115032346:userpool/us-east-1_BUJecylbm"
          export COGNITO_CLIENT_ID="a761ofnfjjo7u5mhpe2r54b7j"
          export LAMBDA_SG="sg-066e845f73d46814d"
          export PRIVATE_SUBNET_1="subnet-0494b6594914ba898"
          export PRIVATE_SUBNET_2="subnet-0f68017cc0b95edda"
          export DATABASE_URL="postgresql://evoadmin:xJB8g6z84PzUYRhWMM8QkkQb@evo-uds-v3-production-postgres.cib8kysoo015.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"
          export FRONTEND_BUCKET="evo-uds-v3-production-frontend-523115032346"
          export CF_DIST_ID="E2NW0IZ2OX493I"
          export S3_BUCKET="evo-sam-artifacts-523115032346"
          export LAMBDA_PREFIX="evo-uds-v3-production"
          export PUBLIC_TEMPLATES_BUCKET="evo-public-templates-523115032346"
          export AZURE_OAUTH_CLIENT_ID="cb8027cd-877e-458a-8f46-b090312f79aa"
          export AZURE_OAUTH_REDIRECT_URI="https://evo.nuevacore.com/azure/callback"
          export APP_DOMAIN="evo.nuevacore.com"
          export API_DOMAIN="api.evo.nuevacore.com"
        else
          export STACK_NAME="evo-uds-v3-sandbox-lambdas"
          export COGNITO_USER_POOL_ID="us-east-1_HPU98xnmT"
          export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:971354623291:userpool/us-east-1_HPU98xnmT"
          export COGNITO_CLIENT_ID="6gls4r44u96v6o0mkm1l6sbmgd"
          export LAMBDA_SG="sg-0f14fd661fc5c41ba"
          export PRIVATE_SUBNET_1="subnet-0edbe4968ff3a5a9e"
          export PRIVATE_SUBNET_2="subnet-01931c820b0b0e864"
          export DATABASE_URL="postgresql://evoadmin:SandboxEvo2026Safe@evo-uds-v3-sandbox-postgres.csno4kowwmc9.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"
          export FRONTEND_BUCKET="evo-uds-v3-sandbox-frontend-971354623291"
          export CF_DIST_ID="E93EL7AJZ6QAQ"
          export S3_BUCKET="evo-sam-artifacts-971354623291"
          export LAMBDA_PREFIX="evo-uds-v3-sandbox"
          export AZURE_OAUTH_CLIENT_ID="cb8027cd-877e-458a-8f46-b090312f79aa"
          export AZURE_OAUTH_REDIRECT_URI="https://evo.sandbox.nuevacore.com/azure/callback"
          export APP_DOMAIN="evo.sandbox.nuevacore.com"
          export API_DOMAIN="api.evo.sandbox.nuevacore.com"
        fi
      - echo "Environment $ENV | Stack $STACK_NAME"
      # Fetch secrets from SSM Parameter Store (secrets not stored in code)
      - |
        # Token Encryption Key
        TOKEN_KEY_PARAM="/evo/${ENV}/token-encryption-key"
        export TOKEN_ENCRYPTION_KEY=$(aws ssm get-parameter --name "$TOKEN_KEY_PARAM" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -z "$TOKEN_ENCRYPTION_KEY" ]; then
          echo "WARNING: TOKEN_ENCRYPTION_KEY not found in SSM ($TOKEN_KEY_PARAM). Token encryption will use fallback."
        else
          echo "TOKEN_ENCRYPTION_KEY loaded from SSM (${TOKEN_ENCRYPTION_KEY:0:5}...)"
        fi

        # Azure OAuth Client Secret
        AZURE_SECRET_PARAM="/evo/${ENV}/azure-oauth-client-secret"
        export AZURE_OAUTH_CLIENT_SECRET=$(aws ssm get-parameter --name "$AZURE_SECRET_PARAM" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -z "$AZURE_OAUTH_CLIENT_SECRET" ]; then
          echo "WARNING: Azure OAuth Client Secret not found in SSM ($AZURE_SECRET_PARAM). Azure OAuth will not work."
        else
          echo "Azure OAuth Client Secret loaded from SSM"
        fi

        # WebAuthn Configuration
        WEBAUTHN_RP_ID_PARAM="/evo/${ENV}/webauthn-rp-id"
        export WEBAUTHN_RP_ID=$(aws ssm get-parameter --name "$WEBAUTHN_RP_ID_PARAM" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -z "$WEBAUTHN_RP_ID" ]; then
          echo "WARNING: WEBAUTHN_RP_ID not found in SSM ($WEBAUTHN_RP_ID_PARAM). Using APP_DOMAIN as fallback."
          export WEBAUTHN_RP_ID="$APP_DOMAIN"
        else
          echo "WEBAUTHN_RP_ID loaded from SSM: $WEBAUTHN_RP_ID"
        fi

        WEBAUTHN_RP_NAME_PARAM="/evo/${ENV}/webauthn-rp-name"
        export WEBAUTHN_RP_NAME=$(aws ssm get-parameter --name "$WEBAUTHN_RP_NAME_PARAM" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -z "$WEBAUTHN_RP_NAME" ]; then
          echo "WEBAUTHN_RP_NAME not found in SSM, will use SAM template default"
        else
          echo "WEBAUTHN_RP_NAME loaded from SSM: $WEBAUTHN_RP_NAME"
        fi

      - echo "=== Analyzing deploy strategy (ALWAYS FULL_SAM for backend) ==="
      - |
        CHANGED_FILES=$(cat /tmp/changed_files.txt)

        DEPLOY_FRONTEND="false"
        DEPLOY_FULL_SAM="false"
        DEPLOY_BACKEND_BUILD="false"
        DEPLOY_FRONTEND_BUILD="false"

        # 1. No git history → full deploy
        if echo "$CHANGED_FILES" | grep -q "FULL_DEPLOY"; then
          echo ">>> FULL DEPLOY (no git history)"
          DEPLOY_FRONTEND="true"
          DEPLOY_FULL_SAM="true"
          DEPLOY_BACKEND_BUILD="true"
          DEPLOY_FRONTEND_BUILD="true"
        fi

        # 2. Any backend change (handlers, lib, types, SAM, prisma) → FULL SAM always
        if [ "$DEPLOY_FULL_SAM" = "false" ] && echo "$CHANGED_FILES" | grep -qE "^(backend/|sam/)"; then
          echo ">>> FULL SAM DEPLOY (backend or SAM changes detected)"
          DEPLOY_FULL_SAM="true"
          DEPLOY_BACKEND_BUILD="true"
        fi

        # 3. Frontend files changed
        if echo "$CHANGED_FILES" | grep -qE "^(src/|public/|index\.html|vite\.config|tailwind|postcss)"; then
          echo ">>> Frontend changed"
          DEPLOY_FRONTEND="true"
          DEPLOY_FRONTEND_BUILD="true"
        fi

        # 4. Backend package.json or tsconfig changed → need backend build
        if echo "$CHANGED_FILES" | grep -qE "^backend/(package\.json|tsconfig\.json)"; then
          DEPLOY_BACKEND_BUILD="true"
        fi

        # If nothing needs deploy
        if [ "$DEPLOY_FULL_SAM" = "false" ] && [ "$DEPLOY_FRONTEND" = "false" ]; then
          echo ">>> NO DEPLOY NEEDED (docs/scripts/cicd only changes)"
        fi

        echo "Deploy strategy: FRONTEND=$DEPLOY_FRONTEND FULL_SAM=$DEPLOY_FULL_SAM"
        echo "Build needed: BACKEND=$DEPLOY_BACKEND_BUILD FRONTEND=$DEPLOY_FRONTEND_BUILD"

        # Persist strategy
        echo "$DEPLOY_FRONTEND" > /tmp/deploy_frontend.txt
        echo "$DEPLOY_FULL_SAM" > /tmp/deploy_full_sam.txt
        echo "$DEPLOY_BACKEND_BUILD" > /tmp/deploy_backend_build.txt
        echo "$DEPLOY_FRONTEND_BUILD" > /tmp/deploy_frontend_build.txt

  build:
    commands:
      - |
        DEPLOY_BACKEND_BUILD=$(cat /tmp/deploy_backend_build.txt)
        DEPLOY_FRONTEND_BUILD=$(cat /tmp/deploy_frontend_build.txt)
        DEPLOY_FULL_SAM=$(cat /tmp/deploy_full_sam.txt)

        # === Build only what's needed ===
        if [ "$DEPLOY_BACKEND_BUILD" = "true" ]; then
          echo "=== Building Backend TypeScript ==="
          npm run build --prefix backend
        else
          echo "=== Skipping Backend Build (no backend changes) ==="
        fi

        if [ "$DEPLOY_FRONTEND_BUILD" = "true" ]; then
          echo "=== Building Frontend ==="
          export VITE_AWS_REGION=us-east-1
          export VITE_AWS_USER_POOL_ID="$COGNITO_USER_POOL_ID"
          export VITE_AWS_USER_POOL_CLIENT_ID="$COGNITO_CLIENT_ID"
          export VITE_WEBAUTHN_RP_ID="$WEBAUTHN_RP_ID"
          export VITE_WEBAUTHN_RP_NAME="$WEBAUTHN_RP_NAME"
          export VITE_ENVIRONMENT="$ENV"
          export VITE_DEMO_EMAIL="comercial+evo@uds.com.br"
          export VITE_DEMO_PASSWORD="Demoevouds@00!"
          if [ "$ENVIRONMENT" = "production" ]; then
            export VITE_AWS_ACCOUNT_ID=523115032346
            export VITE_API_BASE_URL=https://api.evo.nuevacore.com
            export VITE_CLOUDFRONT_DOMAIN=evo.nuevacore.com
            export VITE_STORAGE_ENCRYPTION_KEY="evo-uds-v3-production-secure-key-2024"
          else
            export VITE_AWS_ACCOUNT_ID=971354623291
            export VITE_API_BASE_URL=https://api.evo.sandbox.nuevacore.com
            export VITE_CLOUDFRONT_DOMAIN=evo.sandbox.nuevacore.com
            export VITE_STORAGE_ENCRYPTION_KEY="evo-uds-v3-sandbox-secure-key-2024-local"
          fi
          npm run build:prod
        else
          echo "=== Skipping Frontend Build (no frontend changes) ==="
        fi

        # === Execute deploy strategy — ALWAYS FULL SAM (no incremental) ===
        if [ "$DEPLOY_FULL_SAM" = "true" ]; then
          echo "=== FULL SAM DEPLOY ==="
          # Prepare layer
          mkdir -p backend/layers/dependencies/nodejs/node_modules
          echo "Generating Prisma client..."
          cd backend && npx prisma generate && cd ..
          cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
          cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
          cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
          rm -rf backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin* 2>/dev/null || true

          echo "SAM Build..."
          sam build --template-file sam/production-lambdas-only.yaml --build-dir .aws-sam/build --parallel --cached

          echo "SAM Deploy..."
          PARAM_OVERRIDES="Environment=$ENV"
          PARAM_OVERRIDES="$PARAM_OVERRIDES ProjectName=evo-uds-v3"
          PARAM_OVERRIDES="$PARAM_OVERRIDES DatabaseUrl=$DATABASE_URL"
          PARAM_OVERRIDES="$PARAM_OVERRIDES CognitoUserPoolId=$COGNITO_USER_POOL_ID"
          PARAM_OVERRIDES="$PARAM_OVERRIDES CognitoUserPoolArn=$COGNITO_USER_POOL_ARN"
          PARAM_OVERRIDES="$PARAM_OVERRIDES CognitoClientId=$COGNITO_CLIENT_ID"
          PARAM_OVERRIDES="$PARAM_OVERRIDES LambdaSecurityGroupId=$LAMBDA_SG"
          PARAM_OVERRIDES="$PARAM_OVERRIDES PrivateSubnet1Id=$PRIVATE_SUBNET_1"
          PARAM_OVERRIDES="$PARAM_OVERRIDES PrivateSubnet2Id=$PRIVATE_SUBNET_2"
          PARAM_OVERRIDES="$PARAM_OVERRIDES AzureOAuthClientId=$AZURE_OAUTH_CLIENT_ID"
          PARAM_OVERRIDES="$PARAM_OVERRIDES AzureOAuthRedirectUri=$AZURE_OAUTH_REDIRECT_URI"
          PARAM_OVERRIDES="$PARAM_OVERRIDES AppDomain=$APP_DOMAIN"
          PARAM_OVERRIDES="$PARAM_OVERRIDES ApiDomain=$API_DOMAIN"
          if [ -n "$WEBAUTHN_RP_ID" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES WebAuthnRpId=$WEBAUTHN_RP_ID"
          fi
          if [ -n "$WEBAUTHN_RP_NAME" ] && ! echo "$WEBAUTHN_RP_NAME" | grep -q ' '; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES WebAuthnRpName=$WEBAUTHN_RP_NAME"
          fi
          if [ -n "$TOKEN_ENCRYPTION_KEY" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES TokenEncryptionKey=$TOKEN_ENCRYPTION_KEY"
          fi
          if [ -n "$AZURE_OAUTH_CLIENT_SECRET" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES AzureOAuthClientSecret=$AZURE_OAUTH_CLIENT_SECRET"
          fi

          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name $STACK_NAME \
            --s3-bucket $S3_BUCKET \
            --s3-prefix $STACK_NAME \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
            --region us-east-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides $PARAM_OVERRIDES

        else
          echo "=== NO LAMBDA DEPLOY NEEDED ==="
        fi

  post_build:
    commands:
      - |
        DEPLOY_FRONTEND=$(cat /tmp/deploy_frontend.txt)
        DEPLOY_FULL_SAM=$(cat /tmp/deploy_full_sam.txt)

        if [ "$DEPLOY_FRONTEND" = "true" ]; then
          echo "=== Syncing Frontend to S3 ==="
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          echo "=== Invalidating CloudFront ==="
          aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*" || true

          if [ "$ENVIRONMENT" = "production" ]; then
            echo "=== Syncing CloudFormation template to public bucket ==="
            aws s3 cp dist/cloudformation/evo-platform-role.yaml \
              s3://$PUBLIC_TEMPLATES_BUCKET/cloudformation/evo-platform-role.yaml \
              --content-type "application/x-yaml" || echo "Warning: Could not sync CF template to public bucket"
          fi
        else
          echo "=== Skipping Frontend Deploy (no changes) ==="
        fi

        # Update API Gateway custom domain mapping if full SAM deploy
        if [ "$DEPLOY_FULL_SAM" = "true" ]; then
          CUSTOM_DOMAIN="$API_DOMAIN"
          echo "=== Updating API Gateway Custom Domain Mapping ($CUSTOM_DOMAIN) ==="
          API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 \
            --query "Stacks[0].Outputs[?OutputKey==\`HttpApiId\`].OutputValue" --output text 2>/dev/null || echo "")
          if [ -n "$API_ID" ] && [ "$API_ID" != "None" ]; then
            MAPPING_ID=$(aws apigatewayv2 get-api-mappings --domain-name $CUSTOM_DOMAIN --region us-east-1 \
              --query "Items[0].ApiMappingId" --output text 2>/dev/null || echo "")
            if [ -n "$MAPPING_ID" ] && [ "$MAPPING_ID" != "None" ]; then
              aws apigatewayv2 update-api-mapping \
                --domain-name $CUSTOM_DOMAIN \
                --api-mapping-id $MAPPING_ID \
                --api-id $API_ID \
                --stage prod \
                --region us-east-1 || echo "Warning: Could not update API mapping for $CUSTOM_DOMAIN"
            else
              echo "No existing API mapping found for $CUSTOM_DOMAIN - creating new mapping"
              aws apigatewayv2 create-api-mapping \
                --domain-name $CUSTOM_DOMAIN \
                --api-id $API_ID \
                --stage prod \
                --region us-east-1 || echo "Warning: Could not create API mapping for $CUSTOM_DOMAIN"
            fi
          fi
        fi

        echo "=== DEPLOYMENT COMPLETE ==="
        echo "Strategy used: FRONTEND=$DEPLOY_FRONTEND FULL_SAM=$DEPLOY_FULL_SAM"

        # Ensure dist/ exists for artifacts
        mkdir -p dist
        echo '{"deploy":"ok"}' > dist/deploy-status.json

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - backend/node_modules/**/*
    - node_modules/**/*
    - .aws-sam/cache/**/*
