version: 0.2

# AWS CodeBuild - OPTIMIZED BUILD (No Disk Space Issues)
# Strategy: Build ONCE locally, upload to S3, reference in all Lambdas
# ALL LAMBDAS USE ARM64 ARCHITECTURE (Graviton2) + Node.js 20

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - cd backend && ./node_modules/.bin/prisma generate && cd ..

  pre_build:
    commands:
      - echo "Determining environment..."
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          export ENV="production"
          export AWS_ACCOUNT="523115032346"
          export STACK_NAME="evo-uds-v3-prod-lambdas"
          export CERTIFICATE_ARN="arn:aws:acm:us-east-1:523115032346:certificate/9df982f9-7993-4454-8887-a33e1298b568"
          export FRONTEND_DOMAIN="evo.nuevacore.com"
          export API_DOMAIN="api.evo.nuevacore.com"
          export DB_PASSWORD="${PROD_DB_PASSWORD:-EvoProduction2026SecurePass}"
        else
          export ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
          export STACK_NAME="evo-uds-v3-sandbox-lambdas"
          export CERTIFICATE_ARN=""
          export FRONTEND_DOMAIN=""
          export API_DOMAIN=""
          export DB_PASSWORD="${SANDBOX_DB_PASSWORD:-SandboxPassword2026}"
        fi
      - export S3_BUCKET="evo-sam-artifacts-$AWS_ACCOUNT"
      - echo "Environment $ENV | Account $AWS_ACCOUNT | Stack $STACK_NAME"

  build:
    commands:
      - echo "=== Checking disk space ==="
      - df -h
      
      - echo "=== Step 1 Build TypeScript backend ==="
      - npm run build --prefix backend
      
      - echo "=== Step 2 Build Frontend ==="
      - npm run build
      
      - echo "=== Step 3 Create Lambda Layer (Prisma + Zod ONLY) ==="
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      - rm -rf backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin* 2>/dev/null || true
      - du -sh backend/layers/dependencies/nodejs/node_modules
      
      - echo "=== Step 4 Create Lambda Code Package (handlers + lib + types) ==="
      - mkdir -p /tmp/lambda-package
      - cp -r backend/dist/handlers /tmp/lambda-package/
      - cp -r backend/dist/lib /tmp/lambda-package/
      - cp -r backend/dist/types /tmp/lambda-package/
      
      - echo "=== Step 5 Add ALL dependencies to Lambda package (AWS SDK v3 + Azure SDK) ==="
      - mkdir -p /tmp/lambda-package/node_modules
      - |
        # Copy ONLY essential packages (not all node_modules)
        for pkg in @aws-sdk @smithy @azure zod jsonwebtoken bcryptjs uuid; do
          if [ -d "backend/node_modules/$pkg" ]; then
            cp -r backend/node_modules/$pkg /tmp/lambda-package/node_modules/
          fi
        done
      
      - echo "=== Step 6 Create ZIP and upload to S3 ==="
      - cd /tmp/lambda-package && zip -r -q /tmp/lambda-code.zip . && cd -
      - du -sh /tmp/lambda-code.zip
      - aws s3 cp /tmp/lambda-code.zip s3://$S3_BUCKET/lambda-code/lambda-code-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
      - export LAMBDA_CODE_S3_KEY="lambda-code/lambda-code-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip"
      
      - echo "=== Step 7 Clean up to save disk space ==="
      - rm -rf backend/node_modules
      - rm -rf node_modules
      - rm -rf /tmp/lambda-package
      - df -h
      
      - echo "=== Step 8 Generate minimal SAM template (references S3 code) ==="
      - |
        cat > sam/production-minimal.yaml << 'EOFTEMPLATE'
        AWSTemplateFormatVersion: '2010-09-09'
        Transform: AWS::Serverless-2016-10-31
        Description: EVO Production - Minimal Lambda Deploy

        Parameters:
          Environment:
            Type: String
            Default: production
          ProjectName:
            Type: String
            Default: evo-uds-v3
          DatabasePassword:
            Type: String
            NoEcho: true
          LambdaCodeS3Bucket:
            Type: String
          LambdaCodeS3Key:
            Type: String

        Globals:
          Function:
            Runtime: nodejs20.x
            Timeout: 30
            MemorySize: 256
            Architectures:
              - arm64
            CodeUri:
              Bucket: !Ref LambdaCodeS3Bucket
              Key: !Ref LambdaCodeS3Key
            Layers:
              - !Ref DependenciesLayer

        Resources:
          DependenciesLayer:
            Type: AWS::Serverless::LayerVersion
            Properties:
              LayerName: !Sub '${ProjectName}-${Environment}-deps'
              ContentUri: backend/layers/dependencies/
              CompatibleRuntimes:
                - nodejs20.x
              CompatibleArchitectures:
                - arm64
            Metadata:
              BuildArchitecture: arm64

          # Test Lambda
          TestFunction:
            Type: AWS::Serverless::Function
            Properties:
              FunctionName: !Sub '${ProjectName}-${Environment}-test'
              Handler: handlers/debug/check-daily-costs.handler

        Outputs:
          LayerArn:
            Value: !Ref DependenciesLayer
          TestFunctionArn:
            Value: !GetAtt TestFunction.Arn
        EOFTEMPLATE
      
      - echo "=== Step 9 SAM Build (minimal template, no code copy) ==="
      - sam build --template-file sam/production-minimal.yaml --build-dir .aws-sam/build
      
      - echo "=== Step 10 SAM Deploy ==="
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name ${STACK_NAME}-test \
          --s3-bucket $S3_BUCKET \
          --s3-prefix ${STACK_NAME}-test \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
          --region us-east-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides \
            "Environment=$ENV" \
            "ProjectName=evo-uds-v3" \
            "DatabasePassword=$DB_PASSWORD" \
            "LambdaCodeS3Bucket=$S3_BUCKET" \
            "LambdaCodeS3Key=$LAMBDA_CODE_S3_KEY"

  post_build:
    commands:
      - echo "=== Test Lambda ==="
      - |
        aws lambda invoke \
          --function-name evo-uds-v3-${ENV}-test \
          --region us-east-1 \
          /tmp/test-response.json || true
        cat /tmp/test-response.json || true
      
      - echo "=== DEPLOYMENT COMPLETE ==="
      - echo "Lambda Code S3 Key $LAMBDA_CODE_S3_KEY"
      - df -h

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - .aws-sam/cache/**/*
