version: 0.2

# Test single Lambda deployment - FAST

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --prefix backend
      - npm run build --prefix backend

  build:
    commands:
      - echo "Building single test Lambda..."
      - cp -r backend/dist backend/src
      - cp sam/test-single-lambda.yaml ./test-template.yaml
      - sam build --template-file ./test-template.yaml --build-dir .aws-sam/build
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name evo-test-single-lambda \
          --s3-bucket evo-sam-artifacts-523115032346 \
          --s3-prefix test-lambda \
          --capabilities CAPABILITY_IAM \
          --region us-east-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset

  post_build:
    commands:
      - echo "Test Lambda deployed successfully!"
      - aws lambda get-function --function-name evo-uds-v3-prod-test-function --region us-east-1 --query 'Configuration.FunctionArn' --output text
