version: 0.2

# AWS CodeBuild - SAM Deploy
# Uses existing Lambda stack + deploys frontend infrastructure

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client..."
      - cd backend && npx prisma generate && cd ..

  pre_build:
    commands:
      - echo "Determining environment..."
      - export ENV="sandbox"
      - export AWS_ACCOUNT="971354623291"
      - export LAMBDA_STACK="evo-uds-v3-sandbox-lambdas"
      - export FRONTEND_STACK="evo-uds-v3-sandbox-frontend"
      - echo "Environment is $ENV"
      - echo "Lambda Stack is $LAMBDA_STACK"
      - echo "Frontend Stack is $FRONTEND_STACK"

  build:
    commands:
      - echo "Building TypeScript..."
      - npm run build --prefix backend
      - npm run build
      - echo "Deploying Frontend Stack..."
      - aws cloudformation deploy --template-file sam/frontend-stack.yaml --stack-name $FRONTEND_STACK --parameter-overrides "Environment=$ENV" "ProjectName=evo-uds-v3" --capabilities CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset

  post_build:
    commands:
      - echo "Getting Frontend Stack outputs..."
      - export FRONTEND_BUCKET=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' --output text)
      - export CF_DIST_ID=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' --output text)
      - export CF_DOMAIN=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDomainName`].OutputValue' --output text)
      - echo "Frontend bucket is $FRONTEND_BUCKET"
      - echo "CloudFront ID is $CF_DIST_ID"
      - echo "CloudFront Domain is $CF_DOMAIN"
      - echo "Deploying Frontend files..."
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
      - echo "Deployment completed!"
      - echo "Frontend URL https://$CF_DOMAIN"

artifacts:
  files:
    - dist/**/*
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
