version: 0.2

# AWS CodeBuild - SAM Build and Deploy
# Deploys complete EVO Platform infrastructure via SAM

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "📦 Installing SAM CLI..."
      - pip install aws-sam-cli
      
      - echo "📦 Installing dependencies..."
      - npm ci
      - npm ci --prefix backend
      
      - echo "🔧 Generating Prisma client..."
      - cd backend && npx prisma generate && cd ..

  pre_build:
    commands:
      - echo "🔍 Determining environment..."
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/production" ] || [ "$BRANCH_NAME" = "production" ]; then
          export ENV="production"
          export AWS_ACCOUNT="523115032346"
        else
          export ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
        fi
        export STACK_NAME="evo-uds-v3-$ENV"
        echo "🌍 Environment: $ENV"
        echo "📦 Stack: $STACK_NAME"
        echo "🔢 Account: $AWS_ACCOUNT"

      - echo "🔐 Getting database password from SSM..."
      - |
        export DB_PASSWORD=$(aws ssm get-parameter --name "/evo/$ENV/database-password" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -z "$DB_PASSWORD" ]; then
          echo "⚠️ Database password not found in SSM, generating new one..."
          export DB_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
          aws ssm put-parameter --name "/evo/$ENV/database-password" --value "$DB_PASSWORD" --type SecureString --overwrite || true
        fi

  build:
    commands:
      - echo "🔨 Building TypeScript..."
      - npm run build --prefix backend
      - npm run build
      
      - echo "📝 Generating SAM template..."
      - npx tsx scripts/generate-sam-template.ts
      
      - echo "📦 Preparing Lambda layer (Prisma + zod only)..."
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      
      # Clean up unnecessary files to reduce layer size
      - find backend/layers/dependencies/nodejs/node_modules -name "*.map" -delete 2>/dev/null || true
      - find backend/layers/dependencies/nodejs/node_modules -name "*.md" -delete 2>/dev/null || true
      - find backend/layers/dependencies/nodejs/node_modules -name "*.ts" -not -name "*.d.ts" -delete 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin*.node 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-debian*.node 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-rhel*.node 2>/dev/null || true
      
      # Keep only linux-arm64 engine for Lambda
      - |
        cd backend/layers/dependencies/nodejs/node_modules/.prisma/client
        for f in libquery_engine-*.node; do
          if [[ "$f" != *"linux-arm64"* ]]; then
            rm -f "$f" 2>/dev/null || true
          fi
        done
        cd -
      
      - echo "📊 Layer size:"
      - du -sh backend/layers/dependencies/nodejs/
      
      - echo "🏗️ Building SAM application..."
      - sam build --template-file sam/template.yaml --use-container

  post_build:
    commands:
      - echo "🔍 Checking stack status..."
      - |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
        echo "Stack status: $STACK_STATUS"
        
        if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ] || [ "$STACK_STATUS" = "DELETE_FAILED" ]; then
          echo "🗑️ Deleting stack in $STACK_STATUS state..."
          aws cloudformation delete-stack --stack-name $STACK_NAME --region us-east-1
          echo "⏳ Waiting for stack deletion..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME --region us-east-1 || true
          echo "✅ Stack deleted"
        fi
      
      - echo "🚀 Deploying SAM application..."
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name $STACK_NAME \
          --s3-bucket evo-sam-artifacts-$AWS_ACCOUNT \
          --s3-prefix $STACK_NAME \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --parameter-overrides \
            "Environment=$ENV" \
            "ProjectName=evo-uds-v3" \
            "DatabasePassword=$DB_PASSWORD" \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
      
      - echo "📤 Getting stack outputs..."
      - |
        # Get outputs from CloudFormation
        export FRONTEND_BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' --output text)
        export CF_DIST_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' --output text)
        export API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)
        export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
        export USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text)
        export CF_DOMAIN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDomainName`].OutputValue' --output text)
        
        echo "📋 Stack Outputs:"
        echo "   Frontend Bucket: $FRONTEND_BUCKET"
        echo "   CloudFront ID: $CF_DIST_ID"
        echo "   CloudFront Domain: $CF_DOMAIN"
        echo "   API Endpoint: $API_ENDPOINT"
        echo "   User Pool ID: $USER_POOL_ID"
        echo "   User Pool Client ID: $USER_POOL_CLIENT_ID"
      
      - echo "🌐 Deploying Frontend..."
      - |
        if [ -n "$FRONTEND_BUCKET" ] && [ "$FRONTEND_BUCKET" != "None" ]; then
          echo "📤 Uploading frontend to s3://$FRONTEND_BUCKET/"
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          
          if [ -n "$CF_DIST_ID" ] && [ "$CF_DIST_ID" != "None" ]; then
            echo "🔄 Invalidating CloudFront cache..."
            aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*" || true
          fi
          echo "✅ Frontend deployed!"
        else
          echo "⚠️ Frontend bucket not found in outputs, skipping frontend deploy"
        fi
      
      - echo "📊 Saving outputs to SSM..."
      - |
        aws ssm put-parameter --name "/evo/$ENV/api-endpoint" --value "$API_ENDPOINT" --type String --overwrite || true
        aws ssm put-parameter --name "/evo/$ENV/user-pool-id" --value "$USER_POOL_ID" --type String --overwrite || true
        aws ssm put-parameter --name "/evo/$ENV/user-pool-client-id" --value "$USER_POOL_CLIENT_ID" --type String --overwrite || true
        aws ssm put-parameter --name "/evo/$ENV/frontend-bucket" --value "$FRONTEND_BUCKET" --type String --overwrite || true
        aws ssm put-parameter --name "/evo/$ENV/cloudfront-id" --value "$CF_DIST_ID" --type String --overwrite || true
        aws ssm put-parameter --name "/evo/$ENV/cloudfront-domain" --value "$CF_DOMAIN" --type String --overwrite || true
      
      - echo "🔄 Running database migrations..."
      - |
        # Get DATABASE_URL from secrets manager
        DB_SECRET_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`DatabaseSecretArn`].OutputValue' --output text)
        if [ -n "$DB_SECRET_ARN" ] && [ "$DB_SECRET_ARN" != "None" ]; then
          export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --query 'SecretString' --output text | jq -r '.DATABASE_URL')
          if [ -n "$DATABASE_URL" ]; then
            echo "📦 Running Prisma migrations..."
            cd backend && npx prisma migrate deploy && cd ..
            echo "✅ Migrations completed!"
          fi
        fi
      
      - echo "✅ Deployment completed!"
      - echo ""
      - echo "🎉 EVO Platform deployed successfully!"
      - echo "   Frontend: https://$CF_DOMAIN"
      - echo "   API: $API_ENDPOINT"

artifacts:
  files:
    - .aws-sam/build/template.yaml
    - dist/**/*
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
