version: 0.2

# AWS CodeBuild - SAM Deploy with esbuild
# Layer: Prisma + Zod only (all other deps bundled by esbuild)
# ALL LAMBDAS USE ARM64 ARCHITECTURE (Graviton2)
# esbuild bundles TypeScript directly - no manual tsc build needed

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - cd backend && ./node_modules/.bin/prisma generate && cd ..

  pre_build:
    commands:
      - echo "Determining environment..."
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          export ENV="production"
          export AWS_ACCOUNT="523115032346"
          export STACK_NAME="evo-uds-v3-prod-lambdas"
          export CERTIFICATE_ARN="arn:aws:acm:us-east-1:523115032346:certificate/9df982f9-7993-4454-8887-a33e1298b568"
          export FRONTEND_DOMAIN="evo.nuevacore.com"
          export API_DOMAIN="api.evo.nuevacore.com"
          export DB_PASSWORD="${PROD_DB_PASSWORD:-EvoProduction2026SecurePass}"
        else
          export ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
          export STACK_NAME="evo-uds-v3-sandbox-lambdas"
          export CERTIFICATE_ARN=""
          export FRONTEND_DOMAIN=""
          export API_DOMAIN=""
          export DB_PASSWORD="${SANDBOX_DB_PASSWORD:-SandboxPassword2026}"
        fi
      - export S3_BUCKET="evo-sam-artifacts-$AWS_ACCOUNT"
      - echo "Environment $ENV | Account $AWS_ACCOUNT | Stack $STACK_NAME"

  build:
    commands:
      - echo "=== Step 1 Build Frontend ==="
      - npm run build
      - echo "=== Step 2 Prepare Layer (Prisma + Zod only) ==="
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      - rm -rf backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin* 2>/dev/null || true
      - echo "=== Step 3 Clean up to free disk space ==="
      - rm -rf node_modules/.cache 2>/dev/null || true
      - rm -rf backend/node_modules/.cache 2>/dev/null || true
      - rm -rf .aws-sam/cache 2>/dev/null || true
      - rm -rf /tmp/* 2>/dev/null || true
      - df -h
      - echo "=== Step 4 SAM Build with esbuild (bundles TypeScript directly) ==="
      - sam build --template-file sam/template.yaml --build-dir .aws-sam/build --parallel
      - echo "=== Step 5 Clean build artifacts before deploy ==="
      - find .aws-sam/build -name "*.map" -delete 2>/dev/null || true
      - find .aws-sam/build -name "*.d.ts" -delete 2>/dev/null || true
      - df -h
      - echo "=== Step 6 Deploy SAM Stack ==="
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name $STACK_NAME \
          --s3-bucket $S3_BUCKET \
          --s3-prefix $STACK_NAME \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
          --region us-east-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides "Environment=$ENV" "ProjectName=evo-uds-v3" "DatabasePassword=$DB_PASSWORD"

  post_build:
    commands:
      - echo "=== Getting Stack Outputs ==="
      - export FRONTEND_BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' --output text 2>/dev/null || echo "")
      - export CF_DIST_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' --output text 2>/dev/null || echo "")
      - export DB_SECRET_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`DatabaseSecretArn`].OutputValue' --output text 2>/dev/null || echo "")
      - export API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`ApiId`].OutputValue' --output text 2>/dev/null || echo "")
      - echo "=== Syncing Frontend to S3 ==="
      - |
        if [ -n "$FRONTEND_BUCKET" ]; then
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*" || true
        fi
      - echo "=== Running Database Migrations ==="
      - |
        if [ -n "$DB_SECRET_ARN" ]; then
          export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --region us-east-1 --query 'SecretString' --output text | jq -r '.DATABASE_URL' 2>/dev/null)
          if [ -n "$DATABASE_URL" ] && [ "$DATABASE_URL" != "null" ]; then
            cd backend && ./node_modules/.bin/prisma migrate deploy && cd ..
          fi
        fi
      - echo "=== Configuring API Custom Domain ==="
      - |
        if [ -n "$API_DOMAIN" ] && [ -n "$API_ID" ]; then
          aws cloudformation deploy \
            --template-file sam/api-custom-domain.yaml \
            --stack-name ${STACK_NAME}-api-domain \
            --parameter-overrides "Environment=$ENV" "ProjectName=evo-uds-v3" "ApiDomain=$API_DOMAIN" "CertificateArn=$CERTIFICATE_ARN" "ApiId=$API_ID" "StageName=prod" \
            --capabilities CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset || true
        fi
      - echo "=== DEPLOYMENT COMPLETE ==="
      - echo "Frontend https://${FRONTEND_DOMAIN:-CloudFront}"
      - echo "API https://${API_DOMAIN:-API_Gateway}"
      - echo "=== Cleanup to free disk space ==="
      - rm -rf .aws-sam/build 2>/dev/null || true

artifacts:
  discard-paths: yes
  files:
    - 'version.json'

cache:
  paths:
    - backend/node_modules/**/*
    - node_modules/**/*
