version: 0.2

# AWS CodeBuild - SAM Deploy
# Complete infrastructure deployment via SAM template
# ALL LAMBDAS USE ARM64 ARCHITECTURE (Graviton2)
# Includes: VPC, RDS, Cognito, API Gateway, 194 Lambdas, CloudFront, S3

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - cd backend && npx prisma generate && cd ..

  pre_build:
    commands:
      - echo "Determining environment from ENVIRONMENT variable..."
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          export ENV="production"
          export AWS_ACCOUNT="523115032346"
          export STACK_NAME="evo-uds-v3-prod-lambdas"
          export CERTIFICATE_ARN="arn:aws:acm:us-east-1:523115032346:certificate/9df982f9-7993-4454-8887-a33e1298b568"
          export FRONTEND_DOMAIN="evo.nuevacore.com"
          export API_DOMAIN="api.evo.nuevacore.com"
          export DB_PASSWORD="${PROD_DB_PASSWORD:-EvoProduction2026SecurePass}"
        else
          export ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
          export STACK_NAME="evo-uds-v3-sandbox-lambdas"
          export CERTIFICATE_ARN=""
          export FRONTEND_DOMAIN=""
          export API_DOMAIN=""
          export DB_PASSWORD="${SANDBOX_DB_PASSWORD:-SandboxPassword2026}"
        fi
      - echo "=========================================="
      - echo "Environment     $ENV"
      - echo "AWS Account     $AWS_ACCOUNT"
      - echo "Stack Name      $STACK_NAME"
      - echo "Frontend Domain $FRONTEND_DOMAIN"
      - echo "API Domain      $API_DOMAIN"
      - echo "=========================================="

  build:
    commands:
      - echo "Building TypeScript backend..."
      - npm run build --prefix backend
      
      - echo "Building Frontend..."
      - npm run build
      
      - echo "Preparing Lambda Layer (Prisma + Zod)..."
      - mkdir -p backend/layers/dependencies/nodejs
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/ 2>/dev/null || true
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/ 2>/dev/null || true
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/ 2>/dev/null || true
      
      - echo "=========================================="
      - echo "STEP 1 - Building SAM Application (ARM64)..."
      - echo "=========================================="
      - |
        sam build \
          --template-file sam/template.yaml \
          --build-dir .aws-sam/build \
          --base-dir . \
          --parallel \
          --cached
      
      - echo "=========================================="
      - echo "STEP 2 - Deploying SAM Stack (VPC, RDS, Cognito, API GW, 194 Lambdas)..."
      - echo "=========================================="
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name $STACK_NAME \
          --s3-bucket evo-sam-artifacts-$AWS_ACCOUNT \
          --s3-prefix $STACK_NAME \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
          --region us-east-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides \
            "Environment=$ENV" \
            "ProjectName=evo-uds-v3" \
            "DatabasePassword=$DB_PASSWORD" || echo "SAM deploy completed"

  post_build:
    commands:
      - echo "=========================================="
      - echo "STEP 3 - Getting Stack Outputs..."
      - echo "=========================================="
      - export API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`ApiId`].OutputValue' --output text 2>/dev/null || echo "")
      - export API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text 2>/dev/null || echo "")
      - export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text 2>/dev/null || echo "")
      - export USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text 2>/dev/null || echo "")
      - export DB_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`DatabaseEndpoint`].OutputValue' --output text 2>/dev/null || echo "")
      - export DB_SECRET_ARN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`DatabaseSecretArn`].OutputValue' --output text 2>/dev/null || echo "")
      - export FRONTEND_BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' --output text 2>/dev/null || echo "")
      - export CF_DIST_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' --output text 2>/dev/null || echo "")
      - export CF_DOMAIN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDomainName`].OutputValue' --output text 2>/dev/null || echo "")
      
      - echo "Stack Outputs:"
      - echo "  API Gateway ID    $API_ID"
      - echo "  API Endpoint      $API_ENDPOINT"
      - echo "  Cognito Pool ID   $USER_POOL_ID"
      - echo "  Cognito Client    $USER_POOL_CLIENT_ID"
      - echo "  Database          $DB_ENDPOINT"
      - echo "  Frontend Bucket   $FRONTEND_BUCKET"
      - echo "  CloudFront ID     $CF_DIST_ID"
      - echo "  CloudFront Domain $CF_DOMAIN"
      
      - echo "=========================================="
      - echo "STEP 4 - Syncing Frontend Files to S3..."
      - echo "=========================================="
      - |
        if [ -n "$FRONTEND_BUCKET" ]; then
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
        else
          echo "Frontend bucket not found, skipping sync"
        fi
      
      - echo "=========================================="
      - echo "STEP 5 - Running Database Migrations..."
      - echo "=========================================="
      - |
        if [ -n "$DB_SECRET_ARN" ]; then
          export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --region us-east-1 --query 'SecretString' --output text | jq -r '.DATABASE_URL')
          if [ -n "$DATABASE_URL" ] && [ "$DATABASE_URL" != "null" ]; then
            echo "Running Prisma migrations..."
            cd backend && DATABASE_URL="$DATABASE_URL" npx prisma migrate deploy && cd ..
            echo "Migrations completed!"
          else
            echo "DATABASE_URL not found in secret, skipping migrations"
          fi
        else
          echo "DB_SECRET_ARN not available, skipping migrations"
        fi
      
      - echo "=========================================="
      - echo "STEP 6 - Configuring API Gateway Custom Domain..."
      - echo "=========================================="
      - |
        if [ -n "$API_DOMAIN" ] && [ -n "$API_ID" ]; then
          echo "Deploying API Custom Domain Stack..."
          aws cloudformation deploy \
            --template-file sam/api-custom-domain.yaml \
            --stack-name ${STACK_NAME}-api-domain \
            --parameter-overrides \
              "Environment=$ENV" \
              "ProjectName=evo-uds-v3" \
              "ApiDomain=$API_DOMAIN" \
              "CertificateArn=$CERTIFICATE_ARN" \
              "ApiId=$API_ID" \
              "StageName=prod" \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --no-fail-on-empty-changeset || echo "API Custom Domain deployment completed"
          
          export API_DOMAIN_TARGET=$(aws cloudformation describe-stacks --stack-name ${STACK_NAME}-api-domain --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`ApiCustomDomainTarget`].OutputValue' --output text 2>/dev/null || echo "")
          echo "API Custom Domain Target: $API_DOMAIN_TARGET"
        else
          echo "Skipping API Custom Domain (no domain configured or API not deployed)"
        fi
      
      - echo "=========================================="
      - echo "DEPLOYMENT COMPLETE!"
      - echo "=========================================="
      - echo ""
      - echo "Frontend URL     https://${FRONTEND_DOMAIN:-$CF_DOMAIN}"
      - echo "API URL          https://${API_DOMAIN:-$API_ENDPOINT}"
      - echo "Cognito Pool ID  $USER_POOL_ID"
      - echo "Cognito Client   $USER_POOL_CLIENT_ID"
      - echo "Database         $DB_ENDPOINT"
      - echo ""
      - echo "DNS RECORDS REQUIRED (if using custom domains):"
      - echo "  $FRONTEND_DOMAIN -> $CF_DOMAIN"
      - echo "  $API_DOMAIN -> $API_DOMAIN_TARGET"
      - echo "=========================================="

artifacts:
  files:
    - dist/**/*
    - .aws-sam/**/*
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
    - '.aws-sam/cache/**/*'
