version: 0.2

# AWS CodeBuild - SAM Build and Deploy
# Deploys Lambda functions using existing infrastructure

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "📦 Installing SAM CLI..."
      - pip install aws-sam-cli
      
      - echo "📦 Installing dependencies..."
      - npm install
      - npm install --prefix backend
      
      - echo "🔧 Generating Prisma client..."
      - cd backend && npx prisma generate && cd ..

  pre_build:
    commands:
      - echo "🔍 Determining environment..."
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/production" ] || [ "$BRANCH_NAME" = "production" ]; then
          export ENV="production"
          export AWS_ACCOUNT="523115032346"
          # Production infrastructure values
          export COGNITO_USER_POOL_ID="us-east-1_WVljEXXs9"
          export LAMBDA_SG_ID="sg-07ea931d32276e039"
          export PRIVATE_SUBNET_1="subnet-0af7face420b9f317"
          export PRIVATE_SUBNET_2="subnet-099b0fbc0a342fb0f"
          export LAYER_ARN="arn:aws:lambda:us-east-1:523115032346:layer:evo-prisma-deps-layer:1"
          export DATABASE_URL=$(aws ssm get-parameter --name "/evo/production/database-url" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        else
          export ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
          # Sandbox infrastructure values (existing)
          export COGNITO_USER_POOL_ID="us-east-1_cnesJ48lR"
          export LAMBDA_SG_ID="sg-0f14fd661fc5c41ba"
          export PRIVATE_SUBNET_1="subnet-0edbe4968ff3a5a9e"
          export PRIVATE_SUBNET_2="subnet-01931c820b0b0e864"
          export LAYER_ARN="arn:aws:lambda:us-east-1:971354623291:layer:evo-prisma-deps-layer:92"
          export DATABASE_URL=$(aws ssm get-parameter --name "/evo/sandbox/database-url" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        fi
        echo "🌍 Environment: $ENV"
        echo "📦 Using existing infrastructure"
        echo "🔗 Layer: $LAYER_ARN"

  build:
    commands:
      - echo "🔨 Building TypeScript..."
      - npm run build --prefix backend
      - npm run build
      
      - echo "📝 Generating SAM template..."
      - npx tsx scripts/generate-sam-template.ts
      
      - echo "📦 Preparing Lambda layer (Prisma + zod only)..."
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      
      # Clean up unnecessary files to reduce layer size
      - find backend/layers/dependencies/nodejs/node_modules -name "*.map" -delete 2>/dev/null || true
      - find backend/layers/dependencies/nodejs/node_modules -name "*.md" -delete 2>/dev/null || true
      - find backend/layers/dependencies/nodejs/node_modules -name "*.ts" -not -name "*.d.ts" -delete 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin*.node 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-debian*.node 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-rhel*.node 2>/dev/null || true
      
      # Keep only linux-arm64 engine for Lambda
      - |
        cd backend/layers/dependencies/nodejs/node_modules/.prisma/client
        for f in libquery_engine-*.node; do
          if [[ "$f" != *"linux-arm64"* ]]; then
            rm -f "$f" 2>/dev/null || true
          fi
        done
        cd -
      
      - echo "📊 Layer size:"
      - du -sh backend/layers/dependencies/nodejs/
      
      - echo "🏗️ Building SAM application..."
      - sam build --template-file template.yaml

  post_build:
    commands:
      - echo "🔍 Checking stack status..."
      - |
        STACK_NAME="evo-uds-v3-$ENV-lambdas"
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
        echo "Stack status: $STACK_STATUS"
        
        if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ] || [ "$STACK_STATUS" = "DELETE_FAILED" ]; then
          echo "🗑️ Deleting stack in $STACK_STATUS state..."
          aws cloudformation delete-stack --stack-name $STACK_NAME --region us-east-1
          echo "⏳ Waiting for stack deletion..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME --region us-east-1 || true
          echo "✅ Stack deleted"
        fi
      
      - echo "🚀 Deploying SAM application..."
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name evo-uds-v3-$ENV-lambdas \
          --s3-bucket evo-sam-artifacts-$AWS_ACCOUNT \
          --s3-prefix evo-uds-v3-$ENV \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
          --parameter-overrides \
            "Environment=$ENV" \
            "ProjectName=evo-uds-v3" \
            "DatabaseUrl=$DATABASE_URL" \
            "CognitoUserPoolId=$COGNITO_USER_POOL_ID" \
            "LambdaSecurityGroupId=$LAMBDA_SG_ID" \
            "PrivateSubnet1Id=$PRIVATE_SUBNET_1" \
            "PrivateSubnet2Id=$PRIVATE_SUBNET_2" \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
      
      - echo "🌐 Deploying Frontend..."
      - |
        if [ "$ENV" = "sandbox" ]; then
          FRONTEND_BUCKET="evo-uds-v3-production-frontend-971354623291"
          CF_DIST_ID="E1PY7U3VNT6P1R"
        else
          FRONTEND_BUCKET="evo-uds-v3-prod-frontend-523115032346"
          CF_DIST_ID=""
        fi
        
        if [ -n "$FRONTEND_BUCKET" ]; then
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          
          if [ -n "$CF_DIST_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
          fi
        fi
      
      - echo "✅ Deployment completed!"

artifacts:
  files:
    - .aws-sam/build/template.yaml
    - dist/**/*
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
