version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing esbuild globally..."
      - npm install -g esbuild
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - npm run prisma:generate --prefix backend

  pre_build:
    commands:
      - echo "Determining environment..."
      - export ENV="${ENVIRONMENT:-sandbox}"
      - export AWS_ACCOUNT="${AWS_ACCOUNT_ID:-971354623291}"
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          export STACK_NAME="evo-uds-v3-prod-lambdas"
          export COGNITO_USER_POOL_ID="us-east-1_BUJecylbm"
          export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:523115032346:userpool/us-east-1_BUJecylbm"
          export COGNITO_CLIENT_ID="a761ofnfjjo7u5mhpe2r54b7j"
          export LAMBDA_SG="sg-066e845f73d46814d"
          export PRIVATE_SUBNET_1="subnet-0494b6594914ba898"
          export PRIVATE_SUBNET_2="subnet-0f68017cc0b95edda"
          export DATABASE_URL="postgresql://evoadmin:xJB8g6z84PzUYRhWMM8QkkQb@evo-uds-v3-production-postgres.cib8kysoo015.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"
          export FRONTEND_BUCKET="evo-uds-v3-production-frontend-523115032346"
          export CF_DIST_ID="E2NW0IZ2OX493I"
          export S3_BUCKET="evo-sam-artifacts-523115032346"
        else
          export STACK_NAME="evo-uds-v3-sandbox-lambdas"
          export COGNITO_USER_POOL_ID="us-east-1_HPU98xnmT"
          export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:971354623291:userpool/us-east-1_HPU98xnmT"
          export COGNITO_CLIENT_ID="6gls4r44u96v6o0mkm1l6sbmgd"
          export LAMBDA_SG="sg-0f14fd661fc5c41ba"
          export PRIVATE_SUBNET_1="subnet-0edbe4968ff3a5a9e"
          export PRIVATE_SUBNET_2="subnet-01931c820b0b0e864"
          export DATABASE_URL="postgresql://evoadmin:password@evo-uds-v3-sandbox-postgres.c070y4ceohf7.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"
          export FRONTEND_BUCKET="evo-uds-v3-sandbox-frontend-971354623291"
          export CF_DIST_ID="E93EL7AJZ6QAQ"
          export S3_BUCKET="evo-sam-artifacts-971354623291"
        fi
      - echo "Environment $ENV | Stack $STACK_NAME"

  build:
    commands:
      - echo "=== Step 1 Build TypeScript backend ==="
      - npm run build --prefix backend
      - echo "=== Step 2 Build Frontend ==="
      - npm run build
      - echo "=== Step 3 Prepare Layer (Prisma + Zod only) ==="
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      - rm -rf backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin* 2>/dev/null || true
      - echo "=== Step 4 SAM Build (esbuild for all lambdas) ==="
      - sam build --template-file sam/production-lambdas-only.yaml --build-dir .aws-sam/build --parallel --cached
      - echo "=== Step 5 Deploy SAM Stack ==="
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name $STACK_NAME --s3-bucket $S3_BUCKET --s3-prefix $STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --region us-east-1 --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Environment=$ENV ProjectName=evo-uds-v3 DatabaseUrl=$DATABASE_URL CognitoUserPoolId=$COGNITO_USER_POOL_ID CognitoUserPoolArn=$COGNITO_USER_POOL_ARN CognitoClientId=$COGNITO_CLIENT_ID LambdaSecurityGroupId=$LAMBDA_SG PrivateSubnet1Id=$PRIVATE_SUBNET_1 PrivateSubnet2Id=$PRIVATE_SUBNET_2

  post_build:
    commands:
      - echo "=== Syncing Frontend to S3 ==="
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
      - echo "=== Invalidating CloudFront ==="
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*" || true
      - echo "=== Updating API Gateway Custom Domain Mapping ==="
      - |
        if [ "$ENVIRONMENT" = "production" ]; then
          API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query 'Stacks[0].Outputs[?OutputKey==`HttpApiId`].OutputValue' --output text 2>/dev/null || echo "")
          if [ -n "$API_ID" ] && [ "$API_ID" != "None" ]; then
            echo "Updating custom domain mapping to API: $API_ID"
            MAPPING_ID=$(aws apigatewayv2 get-api-mappings --domain-name api.evo.nuevacore.com --region us-east-1 --query 'Items[0].ApiMappingId' --output text 2>/dev/null || echo "")
            if [ -n "$MAPPING_ID" ] && [ "$MAPPING_ID" != "None" ]; then
              aws apigatewayv2 update-api-mapping --domain-name api.evo.nuevacore.com --api-mapping-id $MAPPING_ID --api-id $API_ID --stage prod --region us-east-1 || echo "Warning: Could not update API mapping"
            fi
          fi
        fi
      - echo "=== DEPLOYMENT COMPLETE ==="

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - backend/node_modules/**/*
    - node_modules/**/*
    - .aws-sam/cache/**/*
