version: 0.2

# AWS CodeBuild - SAM Build and Deploy
# Builds and deploys EVO Platform using AWS SAM

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "ðŸ“¦ Installing SAM CLI..."
      - pip install aws-sam-cli
      
      - echo "ðŸ“¦ Installing dependencies..."
      - npm install
      - npm install --prefix backend
      
      - echo "ðŸ”§ Generating Prisma client..."
      - cd backend && npx prisma generate && cd ..

  pre_build:
    commands:
      - echo "ðŸ” Determining environment..."
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/production" ] || [ "$BRANCH_NAME" = "production" ]; then
          export ENV="production"
          export SAM_CONFIG_ENV="production"
          export AWS_ACCOUNT="523115032346"
          export DATABASE_PASSWORD=$(aws ssm get-parameter --name "/evo/production/database-password" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        else
          export ENV="sandbox"
          export SAM_CONFIG_ENV="sandbox"
          export AWS_ACCOUNT="971354623291"
          export DATABASE_PASSWORD=$(aws ssm get-parameter --name "/evo/sandbox/database-password" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        fi
        echo "ðŸŒ Environment: $ENV"
        echo "ðŸ“¦ SAM config: $SAM_CONFIG_ENV"

  build:
    commands:
      - echo "ðŸ”¨ Building TypeScript..."
      - npm run build --prefix backend
      - npm run build
      
      - echo "ðŸ“ Generating SAM template..."
      - npx tsx scripts/generate-sam-template.ts
      
      - echo "ðŸ“¦ Preparing Lambda layer..."
      - mkdir -p backend/layers/dependencies/nodejs/node_modules
      - cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/
      - cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/
      
      # Copy AWS SDK packages
      - |
        for pkg in @aws-sdk @smithy tslib uuid fast-xml-parser; do
          if [ -d "backend/node_modules/$pkg" ]; then
            cp -r "backend/node_modules/$pkg" backend/layers/dependencies/nodejs/node_modules/
          fi
        done
      
      # Copy Azure SDK packages (if present)
      - |
        for pkg in @azure jsonwebtoken lodash; do
          if [ -d "backend/node_modules/$pkg" ]; then
            cp -r "backend/node_modules/$pkg" backend/layers/dependencies/nodejs/node_modules/
          fi
        done
      
      # Clean up unnecessary files
      - find backend/layers/dependencies/nodejs/node_modules -name "*.map" -delete 2>/dev/null || true
      - find backend/layers/dependencies/nodejs/node_modules -name "*.md" -delete 2>/dev/null || true
      - rm -f backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin*.node 2>/dev/null || true
      
      - echo "ðŸ—ï¸ Packaging SAM application..."
      - echo "Layer directory contents:"
      - ls -la backend/layers/dependencies/nodejs/node_modules/ | head -20 || echo "Layer directory not found"
      - du -sh backend/layers/dependencies/ || echo "Cannot calculate size"
      - echo "Template location:"
      - ls -la template.yaml || echo "Template not found in root"
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket evo-sam-artifacts-$AWS_ACCOUNT --s3-prefix evo-uds-v3-$ENV --region us-east-1

  post_build:
    commands:
      - echo "ðŸš€ Deploying SAM application..."
      - |
        sam deploy \
          --template-file packaged.yaml \
          --stack-name evo-uds-v3-$ENV \
          --s3-bucket evo-sam-artifacts-$AWS_ACCOUNT \
          --s3-prefix evo-uds-v3-$ENV \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            "Environment=$ENV" \
            "ProjectName=evo-uds-v3" \
            "DatabasePassword=$DATABASE_PASSWORD" \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
      
      - echo "ðŸ—„ï¸ Running database migrations..."
      - |
        # Get DATABASE_URL from Secrets Manager
        SECRET_ARN=$(aws cloudformation describe-stacks \
          --stack-name evo-uds-v3-$ENV \
          --query 'Stacks[0].Outputs[?OutputKey==`DatabaseSecretArn`].OutputValue' \
          --output text 2>/dev/null || echo "")
        
        if [ -n "$SECRET_ARN" ]; then
          export DATABASE_URL=$(aws secretsmanager get-secret-value \
            --secret-id $SECRET_ARN \
            --query 'SecretString' \
            --output text | jq -r '.DATABASE_URL')
          
          echo "Applying Prisma migrations..."
          npx prisma migrate deploy --schema=backend/prisma/schema.prisma || echo "âš ï¸ Migration failed"
        fi
      
      - echo "ðŸŒ Deploying Frontend..."
      - |
        FRONTEND_BUCKET=$(aws cloudformation describe-stacks \
          --stack-name evo-uds-v3-$ENV \
          --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' \
          --output text 2>/dev/null || echo "")
        
        if [ -n "$FRONTEND_BUCKET" ]; then
          aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
          
          # Invalidate CloudFront cache
          CF_DIST_ID=$(aws cloudformation describe-stacks \
            --stack-name evo-uds-v3-$ENV \
            --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$CF_DIST_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
          fi
        else
          echo "âš ï¸ Frontend bucket not found in stack outputs"
        fi
      
      - echo "âœ… Deployment completed!"
      - |
        API_ENDPOINT=$(aws cloudformation describe-stacks \
          --stack-name evo-uds-v3-$ENV \
          --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' \
          --output text 2>/dev/null || echo "N/A")
        echo "ðŸ”— API Endpoint: $API_ENDPOINT"

artifacts:
  files:
    - packaged.yaml
    - dist/**/*
  discard-paths: no

cache:
  paths:
    - 'backend/node_modules/**/*'
    - 'node_modules/**/*'
    - '/root/.npm/**/*'
