version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing esbuild globally..."
      - npm install -g esbuild
      - echo "Installing dependencies..."
      - npm install
      - npm install --prefix backend
      - echo "Generating Prisma client for ARM64..."
      - npm run prisma:generate --prefix backend

  pre_build:
    commands:
      - echo "=== Fetching git history for incremental detection ==="
      - 'if [ -d ".git" ]; then echo "Git repo detected"; git fetch --unshallow 2>/dev/null || git fetch --depth=5 origin $CODEBUILD_WEBHOOK_HEAD_REF 2>/dev/null || git fetch --depth=5 2>/dev/null || echo "Git fetch failed"; else echo "No .git directory (CODE_ZIP mode) - cloning with depth=2 for diff..."; git clone --depth=2 --branch production --single-branch https://github.com/rafaesapata/AWS-EVO.git /tmp/git-history 2>/dev/null && export GIT_CLONE_DIR="/tmp/git-history" || echo "Git clone failed"; fi'
      - echo "=== Determining environment ==="
      - export ENV="${ENVIRONMENT:-sandbox}"
      - 'if [ "$ENVIRONMENT" = "production" ]; then export STACK_NAME="evo-uds-v3-prod-lambdas"; export COGNITO_USER_POOL_ID="us-east-1_BUJecylbm"; export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:523115032346:userpool/us-east-1_BUJecylbm"; export COGNITO_CLIENT_ID="a761ofnfjjo7u5mhpe2r54b7j"; export LAMBDA_SG="sg-066e845f73d46814d"; export PRIVATE_SUBNET_1="subnet-0494b6594914ba898"; export PRIVATE_SUBNET_2="subnet-0f68017cc0b95edda"; export DATABASE_URL="postgresql://evoadmin:xJB8g6z84PzUYRhWMM8QkkQb@evo-uds-v3-production-postgres.cib8kysoo015.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"; export FRONTEND_BUCKET="evo-uds-v3-production-frontend-523115032346"; export CF_DIST_ID="E2NW0IZ2OX493I"; export S3_BUCKET="evo-sam-artifacts-523115032346"; export LAMBDA_PREFIX="evo-uds-v3-production"; else export STACK_NAME="evo-uds-v3-sandbox-lambdas"; export COGNITO_USER_POOL_ID="us-east-1_HPU98xnmT"; export COGNITO_USER_POOL_ARN="arn:aws:cognito-idp:us-east-1:971354623291:userpool/us-east-1_HPU98xnmT"; export COGNITO_CLIENT_ID="6gls4r44u96v6o0mkm1l6sbmgd"; export LAMBDA_SG="sg-0f14fd661fc5c41ba"; export PRIVATE_SUBNET_1="subnet-0edbe4968ff3a5a9e"; export PRIVATE_SUBNET_2="subnet-01931c820b0b0e864"; export DATABASE_URL="postgresql://evoadmin:password@evo-uds-v3-sandbox-postgres.c070y4ceohf7.us-east-1.rds.amazonaws.com:5432/evouds?schema=public"; export FRONTEND_BUCKET="evo-uds-v3-sandbox-frontend-971354623291"; export CF_DIST_ID="E93EL7AJZ6QAQ"; export S3_BUCKET="evo-sam-artifacts-971354623291"; export LAMBDA_PREFIX="evo-uds-v3-sandbox"; fi'
      - echo "Environment $ENV | Stack $STACK_NAME"
      - echo "=== Analyzing changed files ==="
      - 'if [ -d ".git" ]; then CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "FULL_DEPLOY"); elif [ -n "$GIT_CLONE_DIR" ] && [ -d "$GIT_CLONE_DIR/.git" ]; then CHANGED_FILES=$(cd $GIT_CLONE_DIR && git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "FULL_DEPLOY"); else CHANGED_FILES="FULL_DEPLOY"; fi'
      - echo "Changed files:" && echo "$CHANGED_FILES"
      - export DEPLOY_FRONTEND="false"
      - export DEPLOY_FULL_SAM="false"
      - export DEPLOY_HANDLERS="false"
      - export DEPLOY_ALL_HANDLERS="false"
      - export CHANGED_HANDLERS=""
      - 'if echo "$CHANGED_FILES" | grep -q "FULL_DEPLOY"; then echo ">>> FULL DEPLOY (no git history)"; export DEPLOY_FRONTEND="true"; export DEPLOY_FULL_SAM="true"; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ] && echo "$CHANGED_FILES" | grep -qE "^(sam/template\.yaml|sam/production-lambdas-only\.yaml|backend/prisma/schema\.prisma)$"; then echo ">>> FULL SAM DEPLOY (SAM template or Prisma schema changed)"; export DEPLOY_FULL_SAM="true"; export DEPLOY_FRONTEND="true"; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ] && echo "$CHANGED_FILES" | grep -qE "^(src/|public/|index\.html|vite\.config|tailwind|postcss)"; then echo ">>> Frontend changed"; export DEPLOY_FRONTEND="true"; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ] && echo "$CHANGED_FILES" | grep -qE "^backend/src/(lib|types)/"; then echo ">>> Shared lib/types changed - incremental deploy of ALL handlers"; export DEPLOY_HANDLERS="true"; export DEPLOY_ALL_HANDLERS="true"; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ]; then HANDLER_CHANGES=$(echo "$CHANGED_FILES" | grep "^backend/src/handlers/" | sed "s|backend/src/handlers/||" || true); if [ -n "$HANDLER_CHANGES" ]; then echo ">>> Handlers changed: $HANDLER_CHANGES"; export DEPLOY_HANDLERS="true"; export CHANGED_HANDLERS="$HANDLER_CHANGES"; fi; fi'
      - echo "Deploy strategy FRONTEND=$DEPLOY_FRONTEND FULL_SAM=$DEPLOY_FULL_SAM HANDLERS=$DEPLOY_HANDLERS ALL_HANDLERS=$DEPLOY_ALL_HANDLERS"

  build:
    commands:
      - echo "=== Building Backend TypeScript ==="
      - npm run build --prefix backend
      - echo "=== Building Frontend ==="
      - npm run build
      - echo "=== Executing deploy strategy ==="
      - 'if [ "$DEPLOY_FULL_SAM" = "true" ]; then echo "=== FULL SAM DEPLOY ==="; mkdir -p backend/layers/dependencies/nodejs/node_modules; cp -r backend/node_modules/@prisma backend/layers/dependencies/nodejs/node_modules/; cp -r backend/node_modules/.prisma backend/layers/dependencies/nodejs/node_modules/; cp -r backend/node_modules/zod backend/layers/dependencies/nodejs/node_modules/; rm -rf backend/layers/dependencies/nodejs/node_modules/.prisma/client/libquery_engine-darwin* 2>/dev/null || true; echo "SAM Build..."; sam build --template-file sam/production-lambdas-only.yaml --build-dir .aws-sam/build --parallel --cached; echo "SAM Deploy..."; sam deploy --template-file .aws-sam/build/template.yaml --stack-name $STACK_NAME --s3-bucket $S3_BUCKET --s3-prefix $STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM --region us-east-1 --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Environment=$ENV ProjectName=evo-uds-v3 DatabaseUrl=$DATABASE_URL CognitoUserPoolId=$COGNITO_USER_POOL_ID CognitoUserPoolArn=$COGNITO_USER_POOL_ARN CognitoClientId=$COGNITO_CLIENT_ID LambdaSecurityGroupId=$LAMBDA_SG PrivateSubnet1Id=$PRIVATE_SUBNET_1 PrivateSubnet2Id=$PRIVATE_SUBNET_2; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ] && [ "$DEPLOY_HANDLERS" = "true" ]; then echo "=== INCREMENTAL LAMBDA DEPLOY ==="; chmod +x cicd/scripts/deploy-changed-lambdas.sh; if [ "$DEPLOY_ALL_HANDLERS" = "true" ]; then echo ">>> Deploying ALL handlers (shared lib/types changed)"; DEPLOY_ALL=true LAMBDA_PREFIX="$LAMBDA_PREFIX" REGION=us-east-1 bash cicd/scripts/deploy-changed-lambdas.sh; else echo ">>> Deploying only changed handlers: $CHANGED_HANDLERS"; CHANGED_HANDLERS="$CHANGED_HANDLERS" LAMBDA_PREFIX="$LAMBDA_PREFIX" REGION=us-east-1 bash cicd/scripts/deploy-changed-lambdas.sh; fi; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "false" ] && [ "$DEPLOY_HANDLERS" = "false" ]; then echo "=== NO LAMBDA CHANGES ==="; fi'

  post_build:
    commands:
      - 'if [ "$DEPLOY_FRONTEND" = "true" ]; then echo "=== Syncing Frontend to S3 ==="; aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete; echo "=== Invalidating CloudFront ==="; aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*" || true; else echo "=== Skipping Frontend Deploy (no changes) ==="; fi'
      - 'if [ "$DEPLOY_FULL_SAM" = "true" ] && [ "$ENVIRONMENT" = "production" ]; then echo "=== Updating API Gateway Custom Domain Mapping ==="; API_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region us-east-1 --query "Stacks[0].Outputs[?OutputKey==\`HttpApiId\`].OutputValue" --output text 2>/dev/null || echo ""); if [ -n "$API_ID" ] && [ "$API_ID" != "None" ]; then MAPPING_ID=$(aws apigatewayv2 get-api-mappings --domain-name api.evo.nuevacore.com --region us-east-1 --query "Items[0].ApiMappingId" --output text 2>/dev/null || echo ""); if [ -n "$MAPPING_ID" ] && [ "$MAPPING_ID" != "None" ]; then aws apigatewayv2 update-api-mapping --domain-name api.evo.nuevacore.com --api-mapping-id $MAPPING_ID --api-id $API_ID --stage prod --region us-east-1 || echo "Warning: Could not update API mapping"; fi; fi; fi'
      - echo "=== DEPLOYMENT COMPLETE ==="
      - echo "Strategy used FRONTEND=$DEPLOY_FRONTEND FULL_SAM=$DEPLOY_FULL_SAM HANDLERS=$DEPLOY_HANDLERS"

artifacts:
  files:
    - dist/**/*

cache:
  paths:
    - backend/node_modules/**/*
    - node_modules/**/*
    - .aws-sam/cache/**/*
