/**
 * Security Engine V2 - ARN Builder
 * Centralized utility for building AWS ARNs - ensures 100% ARN coverage
 */
export declare class ArnBuilder {
    private accountId;
    private partition;
    constructor(accountId: string, partition?: string);
    iamUser(userName: string): string;
    iamRole(roleName: string): string;
    iamPolicy(policyName: string): string;
    iamGroup(groupName: string): string;
    iamAccessKey(userName: string, accessKeyId: string): string;
    iamAccountPasswordPolicy(): string;
    iamRootAccount(): string;
    iamMfaDevice(userName: string, mfaDeviceName: string): string;
    iamSamlProvider(providerName: string): string;
    iamOidcProvider(providerUrl: string): string;
    iamInstanceProfile(profileName: string): string;
    ec2Instance(region: string, instanceId: string): string;
    ec2SecurityGroup(region: string, sgId: string): string;
    ec2Volume(region: string, volumeId: string): string;
    ec2Snapshot(region: string, snapshotId: string): string;
    ec2Vpc(region: string, vpcId: string): string;
    ec2Subnet(region: string, subnetId: string): string;
    ec2NetworkAcl(region: string, naclId: string): string;
    ec2NatGateway(region: string, natId: string): string;
    ec2InternetGateway(region: string, igwId: string): string;
    ec2RouteTable(region: string, rtbId: string): string;
    ec2Ami(region: string, amiId: string): string;
    ec2KeyPair(region: string, keyName: string): string;
    ec2LaunchTemplate(region: string, templateId: string): string;
    ec2ElasticIp(region: string, allocationId: string): string;
    s3Bucket(bucketName: string): string;
    s3Object(bucketName: string, objectKey: string): string;
    s3AccessPoint(region: string, accessPointName: string): string;
    rdsInstance(region: string, dbIdentifier: string): string;
    rdsCluster(region: string, clusterIdentifier: string): string;
    rdsSnapshot(region: string, snapshotIdentifier: string): string;
    rdsClusterSnapshot(region: string, snapshotIdentifier: string): string;
    rdsParameterGroup(region: string, groupName: string): string;
    rdsSubnetGroup(region: string, groupName: string): string;
    rdsProxy(region: string, proxyName: string): string;
    cloudTrail(region: string, trailName: string): string;
    kmsKey(region: string, keyId: string): string;
    kmsAlias(region: string, aliasName: string): string;
    lambdaFunction(region: string, functionName: string): string;
    lambdaLayer(region: string, layerName: string, version: number): string;
    lambdaEventSourceMapping(region: string, uuid: string): string;
    eksCluster(region: string, clusterName: string): string;
    eksNodegroup(region: string, clusterName: string, nodegroupName: string): string;
    eksFargateProfile(region: string, clusterName: string, profileName: string): string;
    eksAddon(region: string, clusterName: string, addonName: string): string;
    ecsCluster(region: string, clusterName: string): string;
    ecsService(region: string, clusterName: string, serviceName: string): string;
    ecsTaskDefinition(region: string, family: string, revision: number): string;
    ecsTask(region: string, clusterName: string, taskId: string): string;
    ecsContainerInstance(region: string, clusterName: string, instanceId: string): string;
    ecrRepository(region: string, repositoryName: string): string;
    apiGatewayRestApi(region: string, apiId: string): string;
    apiGatewayHttpApi(region: string, apiId: string): string;
    apiGatewayStage(region: string, apiId: string, stageName: string): string;
    secretsManagerSecret(region: string, secretId: string): string;
    snsTopic(region: string, topicName: string): string;
    snsSubscription(region: string, topicName: string, subscriptionId: string): string;
    sqsQueue(region: string, queueName: string): string;
    dynamoDBTable(region: string, tableName: string): string;
    dynamoDBStream(region: string, tableName: string, streamLabel: string): string;
    dynamoDBBackup(region: string, tableName: string, backupId: string): string;
    elastiCacheCluster(region: string, clusterId: string): string;
    elastiCacheReplicationGroup(region: string, groupId: string): string;
    elastiCacheSnapshot(region: string, snapshotName: string): string;
    elbv2LoadBalancer(region: string, type: string, name: string, id: string): string;
    elbv2TargetGroup(region: string, targetGroupName: string, id: string): string;
    elbv2Listener(region: string, loadBalancerArn: string, listenerId: string): string;
    cloudFrontDistribution(distributionId: string): string;
    cloudFrontOriginAccessIdentity(oaiId: string): string;
    wafWebAcl(scope: 'regional' | 'global', region: string, name: string, id: string): string;
    wafRuleGroup(scope: 'regional' | 'global', region: string, name: string, id: string): string;
    wafIpSet(scope: 'regional' | 'global', region: string, name: string, id: string): string;
    guardDutyDetector(region: string, detectorId: string): string;
    guardDutyFinding(region: string, detectorId: string, findingId: string): string;
    securityHubHub(region: string): string;
    securityHubFinding(region: string, findingId: string): string;
    configRule(region: string, ruleName: string): string;
    configConformancePack(region: string, packName: string): string;
    acmCertificate(region: string, certificateId: string): string;
    route53HostedZone(hostedZoneId: string): string;
    route53HealthCheck(healthCheckId: string): string;
    efsFileSystem(region: string, fileSystemId: string): string;
    efsAccessPoint(region: string, accessPointId: string): string;
    cognitoUserPool(region: string, userPoolId: string): string;
    cognitoIdentityPool(region: string, identityPoolId: string): string;
    openSearchDomain(region: string, domainName: string): string;
    redshiftCluster(region: string, clusterIdentifier: string): string;
    redshiftSnapshot(region: string, snapshotIdentifier: string): string;
    kinesisStream(region: string, streamName: string): string;
    kinesisFirehose(region: string, deliveryStreamName: string): string;
    cloudWatchLogGroup(region: string, logGroupName: string): string;
    cloudWatchAlarm(region: string, alarmName: string): string;
    eventBridgeEventBus(region: string, eventBusName: string): string;
    eventBridgeRule(region: string, ruleName: string): string;
    stepFunctionsStateMachine(region: string, stateMachineName: string): string;
    stepFunctionsExecution(region: string, stateMachineName: string, executionName: string): string;
    organizationsOrganization(organizationId: string): string;
    organizationsAccount(accountId: string): string;
    organizationsPolicy(policyId: string): string;
    accessAnalyzer(region: string, analyzerName?: string): string;
    generic(service: string, region: string, resourceType: string, resourceId: string): string;
    getAccountId(): string;
    getPartition(): string;
    parseArn(arn: string): {
        partition: string;
        service: string;
        region: string;
        accountId: string;
        resourceType: string;
        resourceId: string;
    } | null;
}
//# sourceMappingURL=arn-builder.d.ts.map