-- Insert comprehensive LGPD compliance checks
INSERT INTO compliance_checks (framework, control_id, control_name, status, severity, remediation_steps) VALUES
-- Princípios da LGPD
('lgpd', 'LGPD-1.1', 'Finalidade - Dados coletados apenas para propósitos legítimos', 'failed', 'high', 'Documente e implemente políticas claras de finalidade para coleta de dados. Revise todos os formulários e pontos de coleta.'),
('lgpd', 'LGPD-1.2', 'Adequação - Compatibilidade com finalidades informadas', 'failed', 'high', 'Valide que o tratamento de dados está alinhado com as finalidades declaradas aos titulares.'),
('lgpd', 'LGPD-1.3', 'Necessidade - Limitação ao mínimo necessário', 'failed', 'critical', 'Revise todos os dados coletados e armazenados. Remova campos desnecessários e implemente coleta por etapas.'),
('lgpd', 'LGPD-1.4', 'Livre Acesso - Consulta facilitada e gratuita', 'failed', 'high', 'Implemente portal de autoatendimento onde titulares possam consultar seus dados gratuitamente.'),
('lgpd', 'LGPD-1.5', 'Qualidade dos Dados - Exatidão, clareza e atualização', 'failed', 'medium', 'Estabeleça processos de validação e atualização periódica dos dados pessoais.'),
('lgpd', 'LGPD-1.6', 'Transparência - Informações claras e acessíveis', 'failed', 'high', 'Publique aviso de privacidade detalhado e de fácil compreensão em todos os pontos de contato.'),
('lgpd', 'LGPD-1.7', 'Segurança - Medidas técnicas e administrativas', 'failed', 'critical', 'Implemente criptografia em repouso e em trânsito, controle de acesso rigoroso e logs de auditoria.'),
('lgpd', 'LGPD-1.8', 'Prevenção - Medidas preventivas contra incidentes', 'failed', 'critical', 'Desenvolva plano de resposta a incidentes, realize testes de invasão e implemente monitoramento 24/7.'),
('lgpd', 'LGPD-1.9', 'Não Discriminação - Proibição de tratamento discriminatório', 'failed', 'high', 'Revise algoritmos e processos decisórios para garantir ausência de viés discriminatório.'),
('lgpd', 'LGPD-1.10', 'Responsabilização - Demonstração de conformidade', 'failed', 'high', 'Mantenha registros detalhados de todas as atividades de tratamento e auditorias regulares.'),

-- Direitos dos Titulares
('lgpd', 'LGPD-2.1', 'Confirmação de Tratamento - Art. 18, I', 'failed', 'high', 'Implemente mecanismo para titular confirmar se seus dados estão sendo tratados.'),
('lgpd', 'LGPD-2.2', 'Acesso aos Dados - Art. 18, II', 'failed', 'critical', 'Forneça acesso completo aos dados pessoais em formato estruturado e legível.'),
('lgpd', 'LGPD-2.3', 'Correção de Dados - Art. 18, III', 'failed', 'high', 'Permita que titulares corrijam dados incompletos, inexatos ou desatualizados.'),
('lgpd', 'LGPD-2.4', 'Anonimização, Bloqueio ou Eliminação - Art. 18, IV', 'failed', 'critical', 'Implemente workflows para anonimizar ou eliminar dados desnecessários ou tratados em desconformidade.'),
('lgpd', 'LGPD-2.5', 'Portabilidade - Art. 18, V', 'failed', 'high', 'Desenvolva funcionalidade para exportar dados em formato interoperável (JSON, CSV, XML).'),
('lgpd', 'LGPD-2.6', 'Eliminação após Término do Tratamento - Art. 18, VI', 'failed', 'critical', 'Configure políticas de retenção e eliminação automática após término da finalidade.'),
('lgpd', 'LGPD-2.7', 'Informação sobre Compartilhamento - Art. 18, VII', 'failed', 'high', 'Liste todas as entidades com quem os dados são compartilhados e mantenha atualizado.'),
('lgpd', 'LGPD-2.8', 'Revogação do Consentimento - Art. 18, IX', 'failed', 'critical', 'Implemente mecanismo simples para revogação de consentimento com efeito imediato.'),
('lgpd', 'LGPD-2.9', 'Oposição ao Tratamento - Art. 18, § 2º', 'failed', 'high', 'Permita que titular se oponha ao tratamento quando baseado em interesse legítimo.'),
('lgpd', 'LGPD-2.10', 'Revisão de Decisões Automatizadas - Art. 20', 'failed', 'critical', 'Implemente revisão humana para decisões automatizadas que afetem interesses dos titulares.'),

-- Bases Legais
('lgpd', 'LGPD-3.1', 'Consentimento - Art. 7º, I', 'failed', 'critical', 'Obtenha consentimento livre, informado e inequívoco. Implemente checkboxes não marcados por padrão.'),
('lgpd', 'LGPD-3.2', 'Cumprimento de Obrigação Legal - Art. 7º, II', 'failed', 'medium', 'Documente obrigações legais que justifiquem o tratamento de dados pessoais.'),
('lgpd', 'LGPD-3.3', 'Execução de Políticas Públicas - Art. 7º, III', 'failed', 'low', 'Se aplicável, documente políticas públicas que fundamentam o tratamento.'),
('lgpd', 'LGPD-3.4', 'Estudos por Órgão de Pesquisa - Art. 7º, IV', 'failed', 'low', 'Anonimize dados quando utilizados para pesquisa, sempre que possível.'),
('lgpd', 'LGPD-3.5', 'Execução de Contrato - Art. 7º, V', 'failed', 'high', 'Limite coleta aos dados estritamente necessários para execução contratual.'),
('lgpd', 'LGPD-3.6', 'Exercício Regular de Direitos - Art. 7º, VI', 'failed', 'medium', 'Documente necessidade de dados para defesa em processos judiciais ou administrativos.'),
('lgpd', 'LGPD-3.7', 'Proteção da Vida - Art. 7º, VII', 'failed', 'critical', 'Implemente procedimentos emergenciais para tratamento de dados em situações de risco.'),
('lgpd', 'LGPD-3.8', 'Tutela da Saúde - Art. 7º, VIII', 'failed', 'critical', 'Garanta conformidade com requisitos específicos para dados de saúde.'),
('lgpd', 'LGPD-3.9', 'Interesse Legítimo - Art. 7º, IX', 'failed', 'high', 'Realize e documente Teste de Balanceamento (LIA) para uso baseado em interesse legítimo.'),
('lgpd', 'LGPD-3.10', 'Proteção do Crédito - Art. 7º, X', 'failed', 'high', 'Se aplicável, garanta conformidade com Lei do Cadastro Positivo.'),

-- Dados Sensíveis (Art. 11)
('lgpd', 'LGPD-4.1', 'Consentimento Específico para Dados Sensíveis', 'failed', 'critical', 'Obtenha consentimento destacado e específico para tratamento de dados sensíveis.'),
('lgpd', 'LGPD-4.2', 'Proteção Extra para Dados de Saúde', 'failed', 'critical', 'Implemente camadas adicionais de segurança para dados de saúde (criptografia, segregação).'),
('lgpd', 'LGPD-4.3', 'Restrição de Tratamento de Dados Biométricos', 'failed', 'critical', 'Avalie necessidade real e implemente segurança máxima para dados biométricos.'),
('lgpd', 'LGPD-4.4', 'Dados sobre Origem Racial/Étnica', 'failed', 'critical', 'Justifique legalmente e proteja rigorosamente dados sobre origem racial ou étnica.'),
('lgpd', 'LGPD-4.5', 'Dados sobre Convicções Religiosas', 'failed', 'critical', 'Minimize coleta e proteja dados sobre convicções religiosas ou filosóficas.'),

-- Crianças e Adolescentes (Art. 14)
('lgpd', 'LGPD-5.1', 'Consentimento Parental para Menores', 'failed', 'critical', 'Implemente verificação de idade e obtenção de consentimento dos pais/responsáveis.'),
('lgpd', 'LGPD-5.2', 'Melhor Interesse da Criança', 'failed', 'critical', 'Garanta que tratamento de dados de menores priorize seu melhor interesse.'),
('lgpd', 'LGPD-5.3', 'Informações Adequadas à Compreensão', 'failed', 'high', 'Adapte linguagem de avisos de privacidade para compreensão de crianças e adolescentes.'),
('lgpd', 'LGPD-5.4', 'Proibição de Contato com Menores', 'failed', 'critical', 'Não utilize dados de crianças para fins comerciais ou publicitários.'),

-- Segurança e Boas Práticas (Art. 46-49)
('lgpd', 'LGPD-6.1', 'Criptografia de Dados em Repouso', 'failed', 'critical', 'Implemente criptografia AES-256 para todos os dados pessoais armazenados.'),
('lgpd', 'LGPD-6.2', 'Criptografia de Dados em Trânsito', 'failed', 'critical', 'Use TLS 1.3 ou superior para transmissão de dados pessoais.'),
('lgpd', 'LGPD-6.3', 'Controle de Acesso Baseado em Função', 'failed', 'critical', 'Implemente RBAC com princípio do menor privilégio para acesso a dados pessoais.'),
('lgpd', 'LGPD-6.4', 'Autenticação Multifator', 'failed', 'critical', 'Exija MFA para acesso a sistemas que processam dados pessoais.'),
('lgpd', 'LGPD-6.5', 'Logs de Auditoria Imutáveis', 'failed', 'high', 'Mantenha logs de todas as operações com dados pessoais por no mínimo 6 meses.'),
('lgpd', 'LGPD-6.6', 'Backups Criptografados', 'failed', 'high', 'Garanta que todos os backups de dados pessoais sejam criptografados.'),
('lgpd', 'LGPD-6.7', 'Segregação de Ambientes', 'failed', 'high', 'Separe ambientes de produção, homologação e desenvolvimento com dados reais.'),
('lgpd', 'LGPD-6.8', 'Testes de Penetração Anuais', 'failed', 'high', 'Realize pentests anuais em sistemas que processam dados pessoais.'),
('lgpd', 'LGPD-6.9', 'Análise de Vulnerabilidades', 'failed', 'high', 'Execute scans de vulnerabilidade mensalmente em infraestrutura crítica.'),
('lgpd', 'LGPD-6.10', 'Gestão de Patches', 'failed', 'critical', 'Aplique patches de segurança críticos em até 72 horas após publicação.'),

-- Transferência Internacional (Art. 33)
('lgpd', 'LGPD-7.1', 'Adequação do País de Destino', 'failed', 'critical', 'Verifique se país de destino possui nível adequado de proteção de dados.'),
('lgpd', 'LGPD-7.2', 'Cláusulas Contratuais Padrão', 'failed', 'high', 'Utilize cláusulas contratuais padrão aprovadas para transferências internacionais.'),
('lgpd', 'LGPD-7.3', 'Normas Corporativas Globais', 'failed', 'medium', 'Se aplicável, estabeleça BCRs (Binding Corporate Rules) aprovadas.'),
('lgpd', 'LGPD-7.4', 'Consentimento Específico para Transferência', 'failed', 'high', 'Obtenha consentimento explícito para transferência internacional quando necessário.'),

-- DPO e Governança (Art. 41)
('lgpd', 'LGPD-8.1', 'Nomeação de Encarregado (DPO)', 'failed', 'critical', 'Nomeie formalmente um Encarregado de Proteção de Dados com qualificação adequada.'),
('lgpd', 'LGPD-8.2', 'Publicação de Identidade do DPO', 'failed', 'high', 'Publique identidade e contato do DPO em canais de comunicação da organização.'),
('lgpd', 'LGPD-8.3', 'Canal de Comunicação com ANPD', 'failed', 'high', 'Estabeleça canal formal para comunicação entre DPO e ANPD.'),
('lgpd', 'LGPD-8.4', 'Registro de Operações de Tratamento (ROPA)', 'failed', 'critical', 'Mantenha registro atualizado de todas as operações de tratamento de dados.'),
('lgpd', 'LGPD-8.5', 'Relatório de Impacto (DPIA)', 'failed', 'critical', 'Realize DPIA para operações de alto risco antes de iniciar tratamento.'),
('lgpd', 'LGPD-8.6', 'Programa de Governança em Privacidade', 'failed', 'high', 'Estabeleça programa formal de governança incluindo políticas, treinamentos e auditorias.'),
('lgpd', 'LGPD-8.7', 'Treinamento de Colaboradores', 'failed', 'high', 'Treine todos os colaboradores em princípios de proteção de dados anualmente.'),
('lgpd', 'LGPD-8.8', 'Resposta a Incidentes de Segurança', 'failed', 'critical', 'Notifique ANPD e titulares em até 72h após ciência de incidente grave.'),

-- GDPR Comprehensive Checks
('gdpr', 'GDPR-1.1', 'Lawfulness of Processing - Art. 6', 'failed', 'critical', 'Establish and document legal basis for all data processing activities.'),
('gdpr', 'GDPR-1.2', 'Fairness and Transparency - Art. 5(1)(a)', 'failed', 'high', 'Process data fairly and provide clear information to data subjects.'),
('gdpr', 'GDPR-1.3', 'Purpose Limitation - Art. 5(1)(b)', 'failed', 'high', 'Collect data only for specified, explicit and legitimate purposes.'),
('gdpr', 'GDPR-1.4', 'Data Minimization - Art. 5(1)(c)', 'failed', 'critical', 'Ensure data is adequate, relevant and limited to what is necessary.'),
('gdpr', 'GDPR-1.5', 'Accuracy - Art. 5(1)(d)', 'failed', 'medium', 'Keep personal data accurate and up to date; erase or rectify without delay.'),
('gdpr', 'GDPR-1.6', 'Storage Limitation - Art. 5(1)(e)', 'failed', 'high', 'Retain data only for as long as necessary for the purposes.'),
('gdpr', 'GDPR-1.7', 'Integrity and Confidentiality - Art. 5(1)(f)', 'failed', 'critical', 'Implement appropriate security measures to protect personal data.'),
('gdpr', 'GDPR-1.8', 'Accountability - Art. 5(2)', 'failed', 'high', 'Demonstrate compliance with GDPR principles through documentation.'),

('gdpr', 'GDPR-2.1', 'Right to be Informed - Art. 13-14', 'failed', 'high', 'Provide privacy notices at point of collection with all required information.'),
('gdpr', 'GDPR-2.2', 'Right of Access - Art. 15', 'failed', 'critical', 'Enable data subjects to access their personal data within one month.'),
('gdpr', 'GDPR-2.3', 'Right to Rectification - Art. 16', 'failed', 'high', 'Allow data subjects to correct inaccurate or incomplete data.'),
('gdpr', 'GDPR-2.4', 'Right to Erasure - Art. 17', 'failed', 'critical', 'Implement right to be forgotten with proper exception handling.'),
('gdpr', 'GDPR-2.5', 'Right to Restrict Processing - Art. 18', 'failed', 'high', 'Enable data subjects to restrict processing under specific conditions.'),
('gdpr', 'GDPR-2.6', 'Right to Data Portability - Art. 20', 'failed', 'high', 'Provide data in machine-readable format for portability.'),
('gdpr', 'GDPR-2.7', 'Right to Object - Art. 21', 'failed', 'high', 'Allow objection to processing for direct marketing and profiling.'),
('gdpr', 'GDPR-2.8', 'Automated Decision Making - Art. 22', 'failed', 'critical', 'Implement safeguards for automated decision-making and profiling.'),

('gdpr', 'GDPR-3.1', 'Consent - Art. 7', 'failed', 'critical', 'Obtain freely given, specific, informed and unambiguous consent.'),
('gdpr', 'GDPR-3.2', 'Children Consent - Art. 8', 'failed', 'critical', 'Verify parental consent for children under 16 (or lower age set by member state).'),
('gdpr', 'GDPR-3.3', 'Withdrawal of Consent - Art. 7(3)', 'failed', 'high', 'Make it as easy to withdraw consent as to give it.'),
('gdpr', 'GDPR-3.4', 'Demonstrable Consent', 'failed', 'high', 'Maintain records proving valid consent was obtained.'),

('gdpr', 'GDPR-4.1', 'Special Categories - Art. 9', 'failed', 'critical', 'Apply heightened protection for sensitive personal data categories.'),
('gdpr', 'GDPR-4.2', 'Processing of Health Data', 'failed', 'critical', 'Ensure health data processing meets Article 9 explicit consent or public interest requirements.'),
('gdpr', 'GDPR-4.3', 'Genetic and Biometric Data', 'failed', 'critical', 'Implement strict controls for genetic and biometric data processing.'),
('gdpr', 'GDPR-4.4', 'Criminal Convictions Data - Art. 10', 'failed', 'critical', 'Process criminal data only under official authority or authorized by law.'),

('gdpr', 'GDPR-5.1', 'DPO Designation - Art. 37', 'failed', 'critical', 'Appoint Data Protection Officer where required and publish contact details.'),
('gdpr', 'GDPR-5.2', 'DPO Independence - Art. 38', 'failed', 'high', 'Ensure DPO operates independently without conflict of interest.'),
('gdpr', 'GDPR-5.3', 'Records of Processing - Art. 30', 'failed', 'critical', 'Maintain comprehensive records of all processing activities (ROPA).'),
('gdpr', 'GDPR-5.4', 'Data Protection Impact Assessment - Art. 35', 'failed', 'critical', 'Conduct DPIA for high-risk processing operations before commencing.'),
('gdpr', 'GDPR-5.5', 'Prior Consultation - Art. 36', 'failed', 'high', 'Consult supervisory authority when DPIA indicates high residual risk.'),

('gdpr', 'GDPR-6.1', 'Security of Processing - Art. 32', 'failed', 'critical', 'Implement state-of-the-art technical and organizational security measures.'),
('gdpr', 'GDPR-6.2', 'Pseudonymization and Encryption', 'failed', 'critical', 'Apply pseudonymization and encryption where appropriate.'),
('gdpr', 'GDPR-6.3', 'Data Breach Notification - Art. 33', 'failed', 'critical', 'Notify supervisory authority within 72 hours of becoming aware of breach.'),
('gdpr', 'GDPR-6.4', 'Communication to Data Subjects - Art. 34', 'failed', 'critical', 'Notify affected individuals of high-risk breaches without undue delay.'),
('gdpr', 'GDPR-6.5', 'Breach Response Plan', 'failed', 'high', 'Establish and test incident response and breach notification procedures.'),

('gdpr', 'GDPR-7.1', 'International Transfers - Art. 44', 'failed', 'critical', 'Ensure transfers to third countries have appropriate safeguards.'),
('gdpr', 'GDPR-7.2', 'Adequacy Decisions - Art. 45', 'failed', 'high', 'Verify adequacy decision exists for destination country.'),
('gdpr', 'GDPR-7.3', 'Standard Contractual Clauses - Art. 46', 'failed', 'high', 'Use approved SCCs and conduct Transfer Impact Assessment.'),
('gdpr', 'GDPR-7.4', 'Binding Corporate Rules - Art. 47', 'failed', 'medium', 'If applicable, establish BCRs approved by competent authority.'),

('gdpr', 'GDPR-8.1', 'Controller-Processor Contracts - Art. 28', 'failed', 'critical', 'Execute written contracts with all processors including mandatory clauses.'),
('gdpr', 'GDPR-8.2', 'Sub-Processor Authorization', 'failed', 'high', 'Obtain prior authorization before processors engage sub-processors.'),
('gdpr', 'GDPR-8.3', 'Processor Due Diligence', 'failed', 'high', 'Conduct thorough assessment of processor security and compliance.'),

-- HIPAA Comprehensive Checks
('hipaa', 'HIPAA-1.1', 'Administrative Safeguards - Security Management', 'failed', 'critical', 'Implement security management process to prevent, detect, contain, and correct security violations.'),
('hipaa', 'HIPAA-1.2', 'Security Officer Designation', 'failed', 'critical', 'Designate a security official responsible for developing and implementing security policies.'),
('hipaa', 'HIPAA-1.3', 'Workforce Security - Authorization', 'failed', 'critical', 'Implement procedures for authorization and supervision of workforce members.'),
('hipaa', 'HIPAA-1.4', 'Workforce Clearance Procedures', 'failed', 'high', 'Determine that workforce access to ePHI is appropriate.'),
('hipaa', 'HIPAA-1.5', 'Termination Procedures', 'failed', 'critical', 'Implement procedures for terminating access to ePHI when employment ends.'),
('hipaa', 'HIPAA-1.6', 'Information Access Management', 'failed', 'critical', 'Implement policies and procedures for authorizing access to ePHI.'),
('hipaa', 'HIPAA-1.7', 'Access Authorization', 'failed', 'high', 'Grant access to ePHI only to authorized persons or software.'),
('hipaa', 'HIPAA-1.8', 'Minimum Necessary Access', 'failed', 'critical', 'Limit access to minimum necessary to accomplish intended purpose.'),
('hipaa', 'HIPAA-1.9', 'Security Awareness Training', 'failed', 'high', 'Provide security training to all workforce members including management.'),
('hipaa', 'HIPAA-1.10', 'Protection from Malware', 'failed', 'critical', 'Implement procedures to guard against malicious software.'),
('hipaa', 'HIPAA-1.11', 'Log-in Monitoring', 'failed', 'high', 'Monitor login attempts and report discrepancies.'),
('hipaa', 'HIPAA-1.12', 'Password Management', 'failed', 'critical', 'Implement procedures for creating, changing, and safeguarding passwords.'),
('hipaa', 'HIPAA-1.13', 'Security Incident Procedures', 'failed', 'critical', 'Implement policies for identifying and responding to security incidents.'),
('hipaa', 'HIPAA-1.14', 'Contingency Planning', 'failed', 'critical', 'Establish data backup, disaster recovery, and emergency operations plans.'),
('hipaa', 'HIPAA-1.15', 'Applications and Data Criticality', 'failed', 'high', 'Assess relative criticality of specific applications and data.'),
('hipaa', 'HIPAA-1.16', 'Business Associate Agreements', 'failed', 'critical', 'Execute written BAAs with all business associates handling PHI.'),
('hipaa', 'HIPAA-1.17', 'Written Contract Requirements', 'failed', 'critical', 'Ensure BAAs contain all required safeguards and provisions.'),

('hipaa', 'HIPAA-2.1', 'Physical Safeguards - Facility Access', 'failed', 'critical', 'Limit physical access to facilities containing ePHI to authorized persons.'),
('hipaa', 'HIPAA-2.2', 'Facility Security Plan', 'failed', 'high', 'Implement policies to safeguard facility and equipment from unauthorized access.'),
('hipaa', 'HIPAA-2.3', 'Access Control and Validation', 'failed', 'critical', 'Implement procedures to control and validate access to facilities.'),
('hipaa', 'HIPAA-2.4', 'Workstation Use Policies', 'failed', 'high', 'Specify proper functions and physical attributes of workstation use.'),
('hipaa', 'HIPAA-2.5', 'Workstation Security', 'failed', 'high', 'Implement physical safeguards for workstations accessing ePHI.'),
('hipaa', 'HIPAA-2.6', 'Device and Media Controls', 'failed', 'critical', 'Implement policies for receipt and removal of hardware and media.'),
('hipaa', 'HIPAA-2.7', 'Media Disposal', 'failed', 'critical', 'Properly dispose of ePHI and hardware/media containing ePHI.'),
('hipaa', 'HIPAA-2.8', 'Media Re-use', 'failed', 'high', 'Remove ePHI before re-using electronic media.'),
('hipaa', 'HIPAA-2.9', 'Data Backup and Storage', 'failed', 'critical', 'Create and maintain retrievable exact copies of ePHI.'),

('hipaa', 'HIPAA-3.1', 'Technical Safeguards - Access Control', 'failed', 'critical', 'Implement technical policies to allow only authorized access to ePHI.'),
('hipaa', 'HIPAA-3.2', 'Unique User Identification', 'failed', 'critical', 'Assign unique identifier for tracking user identity.'),
('hipaa', 'HIPAA-3.3', 'Emergency Access Procedure', 'failed', 'critical', 'Establish procedures for obtaining ePHI during emergency.'),
('hipaa', 'HIPAA-3.4', 'Automatic Logoff', 'failed', 'high', 'Implement automatic logoff after predetermined time of inactivity.'),
('hipaa', 'HIPAA-3.5', 'Encryption and Decryption', 'failed', 'critical', 'Implement mechanism to encrypt and decrypt ePHI as needed.'),
('hipaa', 'HIPAA-3.6', 'Audit Controls', 'failed', 'critical', 'Implement hardware, software, procedures to record and examine ePHI access.'),
('hipaa', 'HIPAA-3.7', 'Integrity Controls', 'failed', 'critical', 'Implement policies to ensure ePHI is not improperly altered or destroyed.'),
('hipaa', 'HIPAA-3.8', 'Authentication', 'failed', 'critical', 'Implement procedures to verify person or entity seeking access is authorized.'),
('hipaa', 'HIPAA-3.9', 'Transmission Security', 'failed', 'critical', 'Implement technical security measures to guard against unauthorized ePHI access during transmission.'),
('hipaa', 'HIPAA-3.10', 'Encryption in Transit', 'failed', 'critical', 'Encrypt ePHI transmitted over electronic networks.'),

('hipaa', 'HIPAA-4.1', 'Privacy Rule - Notice of Privacy Practices', 'failed', 'critical', 'Provide clear notice of privacy practices to all patients.'),
('hipaa', 'HIPAA-4.2', 'Individual Rights - Access', 'failed', 'critical', 'Provide individuals access to their PHI in designated record set.'),
('hipaa', 'HIPAA-4.3', 'Amendment Rights', 'failed', 'high', 'Allow individuals to request amendments to their PHI.'),
('hipaa', 'HIPAA-4.4', 'Accounting of Disclosures', 'failed', 'high', 'Provide accounting of PHI disclosures to individuals upon request.'),
('hipaa', 'HIPAA-4.5', 'Minimum Necessary Standard', 'failed', 'critical', 'Limit PHI uses and disclosures to minimum necessary.'),
('hipaa', 'HIPAA-4.6', 'Authorization Requirements', 'failed', 'critical', 'Obtain valid authorization for uses and disclosures not otherwise permitted.'),
('hipaa', 'HIPAA-4.7', 'Marketing Communications', 'failed', 'high', 'Obtain authorization before using PHI for marketing communications.'),
('hipaa', 'HIPAA-4.8', 'Sale of PHI Restrictions', 'failed', 'critical', 'Obtain authorization and meet requirements before selling PHI.'),

('hipaa', 'HIPAA-5.1', 'Breach Notification - Discovery', 'failed', 'critical', 'Establish procedures to discover and assess potential breaches.'),
('hipaa', 'HIPAA-5.2', 'Risk Assessment', 'failed', 'critical', 'Conduct thorough risk assessment for each suspected breach.'),
('hipaa', 'HIPAA-5.3', 'Individual Notification', 'failed', 'critical', 'Notify affected individuals within 60 days of breach discovery.'),
('hipaa', 'HIPAA-5.4', 'Media Notification', 'failed', 'high', 'Notify media if breach affects 500+ individuals in jurisdiction.'),
('hipaa', 'HIPAA-5.5', 'HHS Notification', 'failed', 'critical', 'Report breaches to HHS Secretary as required by regulation.'),

-- PCI-DSS v4.0 Comprehensive Checks  
('pci-dss', 'PCI-1.1', 'Install and Maintain Network Security Controls', 'failed', 'critical', 'Implement firewalls and routers to protect cardholder data environment.'),
('pci-dss', 'PCI-1.2', 'Network Segmentation', 'failed', 'critical', 'Properly segment cardholder data environment from other networks.'),
('pci-dss', 'PCI-1.3', 'Restrict Inbound/Outbound Traffic', 'failed', 'critical', 'Allow only necessary traffic to/from cardholder data environment.'),
('pci-dss', 'PCI-1.4', 'Wireless Security Standards', 'failed', 'critical', 'Implement strong encryption for wireless transmissions.'),
('pci-dss', 'PCI-1.5', 'Network Diagram Documentation', 'failed', 'high', 'Maintain current network diagrams identifying all connections to CDE.'),

('pci-dss', 'PCI-2.1', 'Change Default Passwords', 'failed', 'critical', 'Change ALL vendor-supplied defaults before deployment.'),
('pci-dss', 'PCI-2.2', 'Configuration Standards', 'failed', 'critical', 'Develop configuration standards for all system components.'),
('pci-dss', 'PCI-2.3', 'Encrypted Admin Access', 'failed', 'critical', 'Encrypt all non-console administrative access using strong cryptography.'),
('pci-dss', 'PCI-2.4', 'Inventory of System Components', 'failed', 'high', 'Maintain inventory of all system components in scope for PCI DSS.'),

('pci-dss', 'PCI-3.1', 'Cardholder Data Retention', 'failed', 'critical', 'Keep cardholder data storage to minimum; document retention policy.'),
('pci-dss', 'PCI-3.2', 'Sensitive Authentication Data', 'failed', 'critical', 'Never store sensitive authentication data after authorization.'),
('pci-dss', 'PCI-3.3', 'PAN Masking', 'failed', 'critical', 'Mask PAN when displayed; show max first 6 and last 4 digits.'),
('pci-dss', 'PCI-3.4', 'PAN Unreadable - Encryption', 'failed', 'critical', 'Render PAN unreadable using strong cryptography.'),
('pci-dss', 'PCI-3.5', 'Key Management Procedures', 'failed', 'critical', 'Document and implement key management processes.'),
('pci-dss', 'PCI-3.6', 'Cryptographic Key Rotation', 'failed', 'high', 'Fully document and implement cryptographic key rotation.'),

('pci-dss', 'PCI-4.1', 'Encryption in Transit', 'failed', 'critical', 'Use strong cryptography for transmission over open, public networks.'),
('pci-dss', 'PCI-4.2', 'Never Send Unprotected PANs', 'failed', 'critical', 'Never send unencrypted PANs via messaging technologies.'),
('pci-dss', 'PCI-4.3', 'TLS Configuration', 'failed', 'critical', 'Implement only strong TLS (1.2+) with secure cipher suites.'),

('pci-dss', 'PCI-5.1', 'Anti-Malware Protection', 'failed', 'critical', 'Deploy anti-malware on all systems commonly affected by malware.'),
('pci-dss', 'PCI-5.2', 'Anti-Malware Updates', 'failed', 'critical', 'Ensure anti-malware mechanisms are current and actively running.'),
('pci-dss', 'PCI-5.3', 'Malware Detection Mechanisms', 'failed', 'high', 'Ensure anti-malware generates audit logs.'),

('pci-dss', 'PCI-6.1', 'Secure Development Processes', 'failed', 'critical', 'Define and implement secure development lifecycle.'),
('pci-dss', 'PCI-6.2', 'Vulnerability Identification', 'failed', 'critical', 'Identify security vulnerabilities using reputable sources.'),
('pci-dss', 'PCI-6.3', 'Security Patch Installation', 'failed', 'critical', 'Install security patches within one month of release.'),
('pci-dss', 'PCI-6.4', 'Payment Application Best Practices', 'failed', 'high', 'Follow payment application vendor security best practices.'),
('pci-dss', 'PCI-6.5', 'Secure Coding Training', 'failed', 'high', 'Train developers in secure coding techniques annually.'),

('pci-dss', 'PCI-7.1', 'Limit Access to System Components', 'failed', 'critical', 'Limit access to system components and cardholder data to need-to-know basis.'),
('pci-dss', 'PCI-7.2', 'Access Control Systems', 'failed', 'critical', 'Establish access control systems with default "deny all" setting.'),
('pci-dss', 'PCI-7.3', 'Access Rights Review', 'failed', 'high', 'Review user access rights at least every six months.'),

('pci-dss', 'PCI-8.1', 'Unique User IDs', 'failed', 'critical', 'Assign unique ID to each person with computer access.'),
('pci-dss', 'PCI-8.2', 'User Authentication Management', 'failed', 'critical', 'Ensure proper user authentication management for all users.'),
('pci-dss', 'PCI-8.3', 'Multi-Factor Authentication', 'failed', 'critical', 'Secure all individual non-console access to CDE with MFA.'),
('pci-dss', 'PCI-8.4', 'Password Requirements', 'failed', 'critical', 'Require minimum 12-character complex passwords.'),
('pci-dss', 'PCI-8.5', 'Password History and Reuse', 'failed', 'high', 'Prevent reuse of last four passwords.'),
('pci-dss', 'PCI-8.6', 'Account Lockout', 'failed', 'critical', 'Lock out account after max 6 invalid access attempts.'),

('pci-dss', 'PCI-9.1', 'Physical Access Controls', 'failed', 'critical', 'Use appropriate facility entry controls to limit physical access.'),
('pci-dss', 'PCI-9.2', 'Physical Access Procedures', 'failed', 'high', 'Develop procedures to distinguish visitors from onsite personnel.'),
('pci-dss', 'PCI-9.3', 'Media Physical Security', 'failed', 'critical', 'Control physical access to media containing cardholder data.'),
('pci-dss', 'PCI-9.4', 'Visitor Authorization', 'failed', 'high', 'Authorize and log all visitor access to facilities.'),

('pci-dss', 'PCI-10.1', 'Audit Trail Implementation', 'failed', 'critical', 'Implement audit trails to link user activities to system components.'),
('pci-dss', 'PCI-10.2', 'Automated Audit Trails', 'failed', 'critical', 'Implement automated audit trails for all system components.'),
('pci-dss', 'PCI-10.3', 'Audit Log Details', 'failed', 'critical', 'Record user ID, type of event, date/time, and affected system component.'),
('pci-dss', 'PCI-10.4', 'Time Synchronization', 'failed', 'critical', 'Synchronize all critical system clocks using NTP or similar.'),
('pci-dss', 'PCI-10.5', 'Audit Log Protection', 'failed', 'critical', 'Secure audit trails so they cannot be altered.'),
('pci-dss', 'PCI-10.6', 'Audit Log Review', 'failed', 'critical', 'Review logs for all system components at least daily.'),
('pci-dss', 'PCI-10.7', 'Audit Log Retention', 'failed', 'high', 'Retain audit trail history for at least 12 months.'),

('pci-dss', 'PCI-11.1', 'Unauthorized Wireless Detection', 'failed', 'critical', 'Test for presence of wireless access points quarterly.'),
('pci-dss', 'PCI-11.2', 'Vulnerability Scanning', 'failed', 'critical', 'Perform quarterly internal and external vulnerability scans.'),
('pci-dss', 'PCI-11.3', 'Penetration Testing', 'failed', 'critical', 'Perform internal and external penetration testing at least annually.'),
('pci-dss', 'PCI-11.4', 'Intrusion Detection Systems', 'failed', 'critical', 'Use intrusion-detection and prevention systems to monitor traffic.'),
('pci-dss', 'PCI-11.5', 'File Integrity Monitoring', 'failed', 'critical', 'Deploy file integrity monitoring to alert on critical file changes.'),

('pci-dss', 'PCI-12.1', 'Information Security Policy', 'failed', 'critical', 'Establish, publish, and maintain security policy.'),
('pci-dss', 'PCI-12.2', 'Risk Assessment Process', 'failed', 'critical', 'Perform annual risk assessment to identify threats and vulnerabilities.'),
('pci-dss', 'PCI-12.3', 'Usage Policies', 'failed', 'high', 'Develop usage policies for critical technologies.'),
('pci-dss', 'PCI-12.4', 'Security Awareness Program', 'failed', 'critical', 'Ensure security awareness training for all personnel annually.'),
('pci-dss', 'PCI-12.5', 'Vendor Management', 'failed', 'critical', 'Assign information security responsibilities to individual or team.'),
('pci-dss', 'PCI-12.6', 'Incident Response Plan', 'failed', 'critical', 'Implement formal incident response plan and test annually.'),
('pci-dss', 'PCI-12.7', 'Service Provider Validation', 'failed', 'critical', 'Validate PCI DSS compliance of service providers annually.'),

-- CIS AWS Foundations Benchmark v1.5 Comprehensive Checks
('cis', 'CIS-1.1', 'Maintain current contact details', 'failed', 'medium', 'Ensure contact email and telephone details for AWS account are current.'),
('cis', 'CIS-1.2', 'Security contact information', 'failed', 'medium', 'Ensure security contact information is registered.'),
('cis', 'CIS-1.3', 'Security questions registered', 'failed', 'low', 'Ensure security questions are registered in AWS account.'),
('cis', 'CIS-1.4', 'No root account access keys', 'failed', 'critical', 'Ensure no root account access key exists.'),
('cis', 'CIS-1.5', 'MFA enabled for root account', 'failed', 'critical', 'Ensure MFA is enabled for root account.'),
('cis', 'CIS-1.6', 'Hardware MFA for root account', 'failed', 'high', 'Ensure hardware MFA is enabled for root account.'),
('cis', 'CIS-1.7', 'Root account usage elimination', 'failed', 'critical', 'Eliminate use of root account for everyday tasks.'),
('cis', 'CIS-1.8', 'Password policy - minimum length', 'failed', 'high', 'Ensure IAM password policy requires minimum length of 14 or greater.'),
('cis', 'CIS-1.9', 'Password policy - prevent reuse', 'failed', 'medium', 'Ensure IAM password policy prevents password reuse.'),
('cis', 'CIS-1.10', 'MFA enabled for IAM users', 'failed', 'critical', 'Ensure multi-factor authentication is enabled for all IAM users.'),
('cis', 'CIS-1.11', 'Expired credentials disabled', 'failed', 'high', 'Do not setup access keys during initial user setup for all IAM users.'),
('cis', 'CIS-1.12', 'Credentials unused for 45 days', 'failed', 'high', 'Ensure credentials unused for 45 days or greater are disabled.'),
('cis', 'CIS-1.13', 'Only one active access key', 'failed', 'medium', 'Ensure there is only one active access key per IAM user.'),
('cis', 'CIS-1.14', 'Access keys rotated 90 days', 'failed', 'high', 'Ensure access keys are rotated every 90 days or less.'),
('cis', 'CIS-1.15', 'Password policy - uppercase requirement', 'failed', 'medium', 'Ensure IAM password policy requires at least one uppercase letter.'),
('cis', 'CIS-1.16', 'Password policy - lowercase requirement', 'failed', 'medium', 'Ensure IAM password policy requires at least one lowercase letter.'),
('cis', 'CIS-1.17', 'Password policy - symbol requirement', 'failed', 'medium', 'Ensure IAM password policy requires at least one symbol.'),
('cis', 'CIS-1.18', 'Password policy - number requirement', 'failed', 'medium', 'Ensure IAM password policy requires at least one number.'),
('cis', 'CIS-1.19', 'Password policy - expiry 90 days', 'failed', 'medium', 'Ensure IAM password policy expires passwords within 90 days or less.'),
('cis', 'CIS-1.20', 'Support role for incident management', 'failed', 'high', 'Ensure a support role has been created for incident management.'),
('cis', 'CIS-1.21', 'Managed policies attached to IAM roles', 'failed', 'low', 'Do not attach IAM policies to groups or roles.'),

('cis', 'CIS-2.1.1', 'S3 Block Public Access - Account level', 'failed', 'critical', 'Ensure S3 Block Public Access is enabled at account level.'),
('cis', 'CIS-2.1.2', 'S3 bucket encryption', 'failed', 'critical', 'Ensure S3 bucket default encryption is enabled.'),
('cis', 'CIS-2.1.3', 'S3 bucket logging enabled', 'failed', 'medium', 'Ensure S3 bucket logging is enabled on all S3 buckets.'),
('cis', 'CIS-2.1.4', 'S3 bucket versioning', 'failed', 'medium', 'Ensure S3 bucket versioning is enabled.'),
('cis', 'CIS-2.1.5', 'S3 lifecycle policies', 'failed', 'low', 'Ensure S3 lifecycle policies are configured.'),
('cis', 'CIS-2.2.1', 'EBS default encryption', 'failed', 'critical', 'Ensure EBS volume encryption is enabled by default.'),
('cis', 'CIS-2.3.1', 'RDS encryption at rest', 'failed', 'critical', 'Ensure RDS instances have encryption enabled.'),
('cis', 'CIS-2.3.2', 'RDS auto minor version upgrade', 'failed', 'high', 'Ensure auto minor version upgrade is enabled for RDS.'),
('cis', 'CIS-2.3.3', 'RDS public accessibility', 'failed', 'critical', 'Ensure RDS instances are not publicly accessible.'),

('cis', 'CIS-3.1', 'CloudTrail enabled all regions', 'failed', 'critical', 'Ensure CloudTrail is enabled in all regions.'),
('cis', 'CIS-3.2', 'CloudTrail log file validation', 'failed', 'high', 'Ensure CloudTrail log file validation is enabled.'),
('cis', 'CIS-3.3', 'CloudTrail S3 bucket access logging', 'failed', 'medium', 'Ensure S3 bucket used for CloudTrail has access logging enabled.'),
('cis', 'CIS-3.4', 'CloudTrail CloudWatch integration', 'failed', 'high', 'Ensure CloudTrail trails are integrated with CloudWatch Logs.'),
('cis', 'CIS-3.5', 'AWS Config enabled all regions', 'failed', 'high', 'Ensure AWS Config is enabled in all regions.'),
('cis', 'CIS-3.6', 'S3 bucket CloudTrail MFA Delete', 'failed', 'medium', 'Ensure S3 bucket for CloudTrail has MFA Delete enabled.'),
('cis', 'CIS-3.7', 'CloudTrail logs encrypted KMS', 'failed', 'high', 'Ensure CloudTrail logs are encrypted at rest using KMS CMKs.'),
('cis', 'CIS-3.8', 'KMS key rotation enabled', 'failed', 'medium', 'Ensure rotation for customer-created CMKs is enabled.'),
('cis', 'CIS-3.9', 'VPC Flow Logging enabled', 'failed', 'high', 'Ensure VPC flow logging is enabled in all VPCs.'),
('cis', 'CIS-3.10', 'Object-level logging S3 write events', 'failed', 'medium', 'Ensure object-level logging for write events is enabled for S3 buckets.'),
('cis', 'CIS-3.11', 'Object-level logging S3 read events', 'failed', 'low', 'Ensure object-level logging for read events is enabled for S3 buckets.'),

('cis', 'CIS-4.1', 'Unauthorized API calls monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for unauthorized API calls.'),
('cis', 'CIS-4.2', 'Console signin without MFA', 'failed', 'high', 'Ensure log metric filter and alarm for Management Console sign-in without MFA.'),
('cis', 'CIS-4.3', 'Root account usage monitoring', 'failed', 'critical', 'Ensure log metric filter and alarm for usage of root account.'),
('cis', 'CIS-4.4', 'IAM policy changes monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for IAM policy changes.'),
('cis', 'CIS-4.5', 'CloudTrail configuration changes', 'failed', 'critical', 'Ensure log metric filter and alarm for CloudTrail configuration changes.'),
('cis', 'CIS-4.6', 'Console authentication failures', 'failed', 'medium', 'Ensure log metric filter and alarm for AWS Management Console authentication failures.'),
('cis', 'CIS-4.7', 'CMK deletion/disabling monitoring', 'failed', 'critical', 'Ensure log metric filter and alarm for disabling or deletion of CMKs.'),
('cis', 'CIS-4.8', 'S3 bucket policy changes', 'failed', 'high', 'Ensure log metric filter and alarm for S3 bucket policy changes.'),
('cis', 'CIS-4.9', 'AWS Config changes monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for AWS Config configuration changes.'),
('cis', 'CIS-4.10', 'Security group changes monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for security group changes.'),
('cis', 'CIS-4.11', 'NACL changes monitoring', 'failed', 'medium', 'Ensure log metric filter and alarm for changes to Network Access Control Lists.'),
('cis', 'CIS-4.12', 'Network gateway changes', 'failed', 'high', 'Ensure log metric filter and alarm for changes to network gateways.'),
('cis', 'CIS-4.13', 'Route table changes monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for route table changes.'),
('cis', 'CIS-4.14', 'VPC changes monitoring', 'failed', 'high', 'Ensure log metric filter and alarm for VPC changes.'),
('cis', 'CIS-4.15', 'Organizations changes monitoring', 'failed', 'medium', 'Ensure log metric filter and alarm for AWS Organizations changes.'),

('cis', 'CIS-5.1', 'No overly permissive security groups', 'failed', 'critical', 'Ensure no security groups allow ingress from 0.0.0.0/0 to port 22.'),
('cis', 'CIS-5.2', 'No RDP from internet', 'failed', 'critical', 'Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389.'),
('cis', 'CIS-5.3', 'Default security group restricts traffic', 'failed', 'high', 'Ensure default security group of VPC restricts all traffic.'),
('cis', 'CIS-5.4', 'VPC peering least privilege routing', 'failed', 'medium', 'Ensure routing tables for VPC peering are least access.');