"use strict";
/**
 * Security Engine V3 - Main Export
 * Military-grade AWS security scanning engine
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.scanDynamoDB = exports.SNSScanner = exports.scanSNS = exports.SQSScanner = exports.scanSQS = exports.WAFScanner = exports.scanWAF = exports.SecurityHubScanner = exports.scanSecurityHub = exports.GuardDutyScanner = exports.scanGuardDuty = exports.KMSScanner = exports.scanKMS = exports.SecretsManagerScanner = exports.scanSecretsManager = exports.CloudTrailScanner = exports.scanCloudTrail = exports.RDSScanner = exports.scanRDS = exports.EC2Scanner = exports.scanEC2 = exports.LambdaScanner = exports.scanLambda = exports.S3Scanner = exports.scanS3 = exports.IAMScanner = exports.scanIAM = exports.runSecurityScan = exports.ScanManager = exports.BaseScanner = exports.BatchProcessor = exports.ParallelExecutor = exports.AWSClientFactory = exports.resetGlobalCache = exports.getGlobalCache = exports.ResourceCache = exports.ArnBuilder = exports.CACHE_TTL = exports.SEVERITY_WEIGHTS = exports.COMPLIANCE_VERSIONS = exports.SENSITIVE_ENV_PATTERNS = exports.DEPRECATED_RUNTIMES = exports.MEDIUM_RISK_PORTS = exports.HIGH_RISK_PORTS = exports.CRITICAL_PORTS = exports.PRIORITY_2_SERVICES = exports.PRIORITY_1_SERVICES = exports.REGIONAL_SERVICES = exports.GLOBAL_SERVICES = exports.DEFAULT_PARALLELIZATION_CONFIG = void 0;
exports.GlueScanner = exports.scanOrganizations = exports.OrganizationsScanner = exports.scanNetworkFirewall = exports.NetworkFirewallScanner = exports.scanMacie = exports.MacieScanner = exports.scanInspector = exports.InspectorScanner = exports.scanKinesis = exports.KinesisScanner = exports.scanSSM = exports.SSMScanner = exports.scanStepFunctions = exports.StepFunctionsScanner = exports.scanEventBridge = exports.EventBridgeScanner = exports.scanRedshift = exports.RedshiftScanner = exports.scanCloudWatch = exports.CloudWatchScanner = exports.scanBackup = exports.BackupScanner = exports.scanConfig = exports.ConfigScanner = exports.scanEFS = exports.EFSScanner = exports.scanRoute53 = exports.Route53Scanner = exports.scanECR = exports.ECRScanner = exports.OpenSearchScanner = exports.scanOpenSearch = exports.ECSScanner = exports.scanECS = exports.EKSScanner = exports.scanEKS = exports.ELBScanner = exports.scanELB = exports.ElastiCacheScanner = exports.scanElastiCache = exports.CloudFrontScanner = exports.scanCloudFront = exports.ACMScanner = exports.scanACM = exports.APIGatewayScanner = exports.scanAPIGateway = exports.CognitoScanner = exports.scanCognito = exports.DynamoDBScanner = void 0;
exports.scanGlue = void 0;
// Configuration
var config_js_1 = require("./config.js");
Object.defineProperty(exports, "DEFAULT_PARALLELIZATION_CONFIG", { enumerable: true, get: function () { return config_js_1.DEFAULT_PARALLELIZATION_CONFIG; } });
Object.defineProperty(exports, "GLOBAL_SERVICES", { enumerable: true, get: function () { return config_js_1.GLOBAL_SERVICES; } });
Object.defineProperty(exports, "REGIONAL_SERVICES", { enumerable: true, get: function () { return config_js_1.REGIONAL_SERVICES; } });
Object.defineProperty(exports, "PRIORITY_1_SERVICES", { enumerable: true, get: function () { return config_js_1.PRIORITY_1_SERVICES; } });
Object.defineProperty(exports, "PRIORITY_2_SERVICES", { enumerable: true, get: function () { return config_js_1.PRIORITY_2_SERVICES; } });
Object.defineProperty(exports, "CRITICAL_PORTS", { enumerable: true, get: function () { return config_js_1.CRITICAL_PORTS; } });
Object.defineProperty(exports, "HIGH_RISK_PORTS", { enumerable: true, get: function () { return config_js_1.HIGH_RISK_PORTS; } });
Object.defineProperty(exports, "MEDIUM_RISK_PORTS", { enumerable: true, get: function () { return config_js_1.MEDIUM_RISK_PORTS; } });
Object.defineProperty(exports, "DEPRECATED_RUNTIMES", { enumerable: true, get: function () { return config_js_1.DEPRECATED_RUNTIMES; } });
Object.defineProperty(exports, "SENSITIVE_ENV_PATTERNS", { enumerable: true, get: function () { return config_js_1.SENSITIVE_ENV_PATTERNS; } });
Object.defineProperty(exports, "COMPLIANCE_VERSIONS", { enumerable: true, get: function () { return config_js_1.COMPLIANCE_VERSIONS; } });
Object.defineProperty(exports, "SEVERITY_WEIGHTS", { enumerable: true, get: function () { return config_js_1.SEVERITY_WEIGHTS; } });
Object.defineProperty(exports, "CACHE_TTL", { enumerable: true, get: function () { return config_js_1.CACHE_TTL; } });
// Core components
var arn_builder_js_1 = require("./arn-builder.js");
Object.defineProperty(exports, "ArnBuilder", { enumerable: true, get: function () { return arn_builder_js_1.ArnBuilder; } });
var resource_cache_js_1 = require("./core/resource-cache.js");
Object.defineProperty(exports, "ResourceCache", { enumerable: true, get: function () { return resource_cache_js_1.ResourceCache; } });
Object.defineProperty(exports, "getGlobalCache", { enumerable: true, get: function () { return resource_cache_js_1.getGlobalCache; } });
Object.defineProperty(exports, "resetGlobalCache", { enumerable: true, get: function () { return resource_cache_js_1.resetGlobalCache; } });
var client_factory_js_1 = require("./core/client-factory.js");
Object.defineProperty(exports, "AWSClientFactory", { enumerable: true, get: function () { return client_factory_js_1.AWSClientFactory; } });
var parallel_executor_js_1 = require("./core/parallel-executor.js");
Object.defineProperty(exports, "ParallelExecutor", { enumerable: true, get: function () { return parallel_executor_js_1.ParallelExecutor; } });
Object.defineProperty(exports, "BatchProcessor", { enumerable: true, get: function () { return parallel_executor_js_1.BatchProcessor; } });
var base_scanner_js_1 = require("./core/base-scanner.js");
Object.defineProperty(exports, "BaseScanner", { enumerable: true, get: function () { return base_scanner_js_1.BaseScanner; } });
var scan_manager_js_1 = require("./core/scan-manager.js");
Object.defineProperty(exports, "ScanManager", { enumerable: true, get: function () { return scan_manager_js_1.ScanManager; } });
Object.defineProperty(exports, "runSecurityScan", { enumerable: true, get: function () { return scan_manager_js_1.runSecurityScan; } });
// Individual scanners
var index_js_1 = require("./scanners/iam/index.js");
Object.defineProperty(exports, "scanIAM", { enumerable: true, get: function () { return index_js_1.scanIAM; } });
Object.defineProperty(exports, "IAMScanner", { enumerable: true, get: function () { return index_js_1.IAMScanner; } });
var index_js_2 = require("./scanners/s3/index.js");
Object.defineProperty(exports, "scanS3", { enumerable: true, get: function () { return index_js_2.scanS3; } });
Object.defineProperty(exports, "S3Scanner", { enumerable: true, get: function () { return index_js_2.S3Scanner; } });
var index_js_3 = require("./scanners/lambda/index.js");
Object.defineProperty(exports, "scanLambda", { enumerable: true, get: function () { return index_js_3.scanLambda; } });
Object.defineProperty(exports, "LambdaScanner", { enumerable: true, get: function () { return index_js_3.LambdaScanner; } });
var index_js_4 = require("./scanners/ec2/index.js");
Object.defineProperty(exports, "scanEC2", { enumerable: true, get: function () { return index_js_4.scanEC2; } });
Object.defineProperty(exports, "EC2Scanner", { enumerable: true, get: function () { return index_js_4.EC2Scanner; } });
var index_js_5 = require("./scanners/rds/index.js");
Object.defineProperty(exports, "scanRDS", { enumerable: true, get: function () { return index_js_5.scanRDS; } });
Object.defineProperty(exports, "RDSScanner", { enumerable: true, get: function () { return index_js_5.RDSScanner; } });
var index_js_6 = require("./scanners/cloudtrail/index.js");
Object.defineProperty(exports, "scanCloudTrail", { enumerable: true, get: function () { return index_js_6.scanCloudTrail; } });
Object.defineProperty(exports, "CloudTrailScanner", { enumerable: true, get: function () { return index_js_6.CloudTrailScanner; } });
var index_js_7 = require("./scanners/secrets-manager/index.js");
Object.defineProperty(exports, "scanSecretsManager", { enumerable: true, get: function () { return index_js_7.scanSecretsManager; } });
Object.defineProperty(exports, "SecretsManagerScanner", { enumerable: true, get: function () { return index_js_7.SecretsManagerScanner; } });
var index_js_8 = require("./scanners/kms/index.js");
Object.defineProperty(exports, "scanKMS", { enumerable: true, get: function () { return index_js_8.scanKMS; } });
Object.defineProperty(exports, "KMSScanner", { enumerable: true, get: function () { return index_js_8.KMSScanner; } });
var index_js_9 = require("./scanners/guardduty/index.js");
Object.defineProperty(exports, "scanGuardDuty", { enumerable: true, get: function () { return index_js_9.scanGuardDuty; } });
Object.defineProperty(exports, "GuardDutyScanner", { enumerable: true, get: function () { return index_js_9.GuardDutyScanner; } });
var index_js_10 = require("./scanners/security-hub/index.js");
Object.defineProperty(exports, "scanSecurityHub", { enumerable: true, get: function () { return index_js_10.scanSecurityHub; } });
Object.defineProperty(exports, "SecurityHubScanner", { enumerable: true, get: function () { return index_js_10.SecurityHubScanner; } });
var index_js_11 = require("./scanners/waf/index.js");
Object.defineProperty(exports, "scanWAF", { enumerable: true, get: function () { return index_js_11.scanWAF; } });
Object.defineProperty(exports, "WAFScanner", { enumerable: true, get: function () { return index_js_11.WAFScanner; } });
var index_js_12 = require("./scanners/sqs/index.js");
Object.defineProperty(exports, "scanSQS", { enumerable: true, get: function () { return index_js_12.scanSQS; } });
Object.defineProperty(exports, "SQSScanner", { enumerable: true, get: function () { return index_js_12.SQSScanner; } });
var index_js_13 = require("./scanners/sns/index.js");
Object.defineProperty(exports, "scanSNS", { enumerable: true, get: function () { return index_js_13.scanSNS; } });
Object.defineProperty(exports, "SNSScanner", { enumerable: true, get: function () { return index_js_13.SNSScanner; } });
var index_js_14 = require("./scanners/dynamodb/index.js");
Object.defineProperty(exports, "scanDynamoDB", { enumerable: true, get: function () { return index_js_14.scanDynamoDB; } });
Object.defineProperty(exports, "DynamoDBScanner", { enumerable: true, get: function () { return index_js_14.DynamoDBScanner; } });
var index_js_15 = require("./scanners/cognito/index.js");
Object.defineProperty(exports, "scanCognito", { enumerable: true, get: function () { return index_js_15.scanCognito; } });
Object.defineProperty(exports, "CognitoScanner", { enumerable: true, get: function () { return index_js_15.CognitoScanner; } });
var index_js_16 = require("./scanners/api-gateway/index.js");
Object.defineProperty(exports, "scanAPIGateway", { enumerable: true, get: function () { return index_js_16.scanAPIGateway; } });
Object.defineProperty(exports, "APIGatewayScanner", { enumerable: true, get: function () { return index_js_16.APIGatewayScanner; } });
var index_js_17 = require("./scanners/acm/index.js");
Object.defineProperty(exports, "scanACM", { enumerable: true, get: function () { return index_js_17.scanACM; } });
Object.defineProperty(exports, "ACMScanner", { enumerable: true, get: function () { return index_js_17.ACMScanner; } });
var index_js_18 = require("./scanners/cloudfront/index.js");
Object.defineProperty(exports, "scanCloudFront", { enumerable: true, get: function () { return index_js_18.scanCloudFront; } });
Object.defineProperty(exports, "CloudFrontScanner", { enumerable: true, get: function () { return index_js_18.CloudFrontScanner; } });
var index_js_19 = require("./scanners/elasticache/index.js");
Object.defineProperty(exports, "scanElastiCache", { enumerable: true, get: function () { return index_js_19.scanElastiCache; } });
Object.defineProperty(exports, "ElastiCacheScanner", { enumerable: true, get: function () { return index_js_19.ElastiCacheScanner; } });
var index_js_20 = require("./scanners/elb/index.js");
Object.defineProperty(exports, "scanELB", { enumerable: true, get: function () { return index_js_20.scanELB; } });
Object.defineProperty(exports, "ELBScanner", { enumerable: true, get: function () { return index_js_20.ELBScanner; } });
var index_js_21 = require("./scanners/eks/index.js");
Object.defineProperty(exports, "scanEKS", { enumerable: true, get: function () { return index_js_21.scanEKS; } });
Object.defineProperty(exports, "EKSScanner", { enumerable: true, get: function () { return index_js_21.EKSScanner; } });
var index_js_22 = require("./scanners/ecs/index.js");
Object.defineProperty(exports, "scanECS", { enumerable: true, get: function () { return index_js_22.scanECS; } });
Object.defineProperty(exports, "ECSScanner", { enumerable: true, get: function () { return index_js_22.ECSScanner; } });
var index_js_23 = require("./scanners/opensearch/index.js");
Object.defineProperty(exports, "scanOpenSearch", { enumerable: true, get: function () { return index_js_23.scanOpenSearch; } });
Object.defineProperty(exports, "OpenSearchScanner", { enumerable: true, get: function () { return index_js_23.OpenSearchScanner; } });
// New scanners - Phase 2
var index_js_24 = require("./scanners/ecr/index.js");
Object.defineProperty(exports, "ECRScanner", { enumerable: true, get: function () { return index_js_24.ECRScanner; } });
Object.defineProperty(exports, "scanECR", { enumerable: true, get: function () { return index_js_24.scanECR; } });
var index_js_25 = require("./scanners/route53/index.js");
Object.defineProperty(exports, "Route53Scanner", { enumerable: true, get: function () { return index_js_25.Route53Scanner; } });
Object.defineProperty(exports, "scanRoute53", { enumerable: true, get: function () { return index_js_25.scanRoute53; } });
var index_js_26 = require("./scanners/efs/index.js");
Object.defineProperty(exports, "EFSScanner", { enumerable: true, get: function () { return index_js_26.EFSScanner; } });
Object.defineProperty(exports, "scanEFS", { enumerable: true, get: function () { return index_js_26.scanEFS; } });
var index_js_27 = require("./scanners/config/index.js");
Object.defineProperty(exports, "ConfigScanner", { enumerable: true, get: function () { return index_js_27.ConfigScanner; } });
Object.defineProperty(exports, "scanConfig", { enumerable: true, get: function () { return index_js_27.scanConfig; } });
var index_js_28 = require("./scanners/backup/index.js");
Object.defineProperty(exports, "BackupScanner", { enumerable: true, get: function () { return index_js_28.BackupScanner; } });
Object.defineProperty(exports, "scanBackup", { enumerable: true, get: function () { return index_js_28.scanBackup; } });
var index_js_29 = require("./scanners/cloudwatch/index.js");
Object.defineProperty(exports, "CloudWatchScanner", { enumerable: true, get: function () { return index_js_29.CloudWatchScanner; } });
Object.defineProperty(exports, "scanCloudWatch", { enumerable: true, get: function () { return index_js_29.scanCloudWatch; } });
var index_js_30 = require("./scanners/redshift/index.js");
Object.defineProperty(exports, "RedshiftScanner", { enumerable: true, get: function () { return index_js_30.RedshiftScanner; } });
Object.defineProperty(exports, "scanRedshift", { enumerable: true, get: function () { return index_js_30.scanRedshift; } });
// New scanners - Phase 3
var index_js_31 = require("./scanners/eventbridge/index.js");
Object.defineProperty(exports, "EventBridgeScanner", { enumerable: true, get: function () { return index_js_31.EventBridgeScanner; } });
Object.defineProperty(exports, "scanEventBridge", { enumerable: true, get: function () { return index_js_31.scanEventBridge; } });
var index_js_32 = require("./scanners/stepfunctions/index.js");
Object.defineProperty(exports, "StepFunctionsScanner", { enumerable: true, get: function () { return index_js_32.StepFunctionsScanner; } });
Object.defineProperty(exports, "scanStepFunctions", { enumerable: true, get: function () { return index_js_32.scanStepFunctions; } });
var index_js_33 = require("./scanners/ssm/index.js");
Object.defineProperty(exports, "SSMScanner", { enumerable: true, get: function () { return index_js_33.SSMScanner; } });
Object.defineProperty(exports, "scanSSM", { enumerable: true, get: function () { return index_js_33.scanSSM; } });
var index_js_34 = require("./scanners/kinesis/index.js");
Object.defineProperty(exports, "KinesisScanner", { enumerable: true, get: function () { return index_js_34.KinesisScanner; } });
Object.defineProperty(exports, "scanKinesis", { enumerable: true, get: function () { return index_js_34.scanKinesis; } });
var index_js_35 = require("./scanners/inspector/index.js");
Object.defineProperty(exports, "InspectorScanner", { enumerable: true, get: function () { return index_js_35.InspectorScanner; } });
Object.defineProperty(exports, "scanInspector", { enumerable: true, get: function () { return index_js_35.scanInspector; } });
var index_js_36 = require("./scanners/macie/index.js");
Object.defineProperty(exports, "MacieScanner", { enumerable: true, get: function () { return index_js_36.MacieScanner; } });
Object.defineProperty(exports, "scanMacie", { enumerable: true, get: function () { return index_js_36.scanMacie; } });
var index_js_37 = require("./scanners/networkfirewall/index.js");
Object.defineProperty(exports, "NetworkFirewallScanner", { enumerable: true, get: function () { return index_js_37.NetworkFirewallScanner; } });
Object.defineProperty(exports, "scanNetworkFirewall", { enumerable: true, get: function () { return index_js_37.scanNetworkFirewall; } });
var index_js_38 = require("./scanners/organizations/index.js");
Object.defineProperty(exports, "OrganizationsScanner", { enumerable: true, get: function () { return index_js_38.OrganizationsScanner; } });
Object.defineProperty(exports, "scanOrganizations", { enumerable: true, get: function () { return index_js_38.scanOrganizations; } });
// New scanners - Sprint 1 Evolution (Missing Services)
var index_js_39 = require("./scanners/glue/index.js");
Object.defineProperty(exports, "GlueScanner", { enumerable: true, get: function () { return index_js_39.GlueScanner; } });
Object.defineProperty(exports, "scanGlue", { enumerable: true, get: function () { return index_js_39.scanGlue; } });
//# sourceMappingURL=index.js.map